### ISSUE TITLE
Update HubSpot form on contact's page

### ISSUE THREAD

**Issue by Shih-Yu** [livepeer/studio#1009]
**Title**
Update new HubSpot form

**Description**
Update the existing form on [Contact page](https://livepeer.com/contact) with the new Hubspot form, keeping the same styling as the website.

**To Reproduce (required) Steps to reproduce the behavior:**
When going to the link provided in the description, it should display the new form from HubSpot with the code provided.

**Device (required):**
Here is the embedded code for the form:

```
<!--[if lte IE 8]>
<script charset="utf-8" type="text/javascript" src="//js.hsforms.net/forms/v2-legacy.js"></script>
<![endif]-->
<script charset="utf-8" type="text/javascript" src="//js.hsforms.net/forms/v2.js"></script>
<script>
  hbspt.forms.create({
	region: "na1",
	portalId: "6160488",
	formId: "178f8cb9-1fa9-4fe8-a6ca-706f3bd31c7a"
});
</script>
```

**Screenshots**
![Screen Shot 2022-04-15 at 2.30.02 PM.png](https://images.zenhubusercontent.com/61fdb1f02502ef1db9860e14/843250cf-2e91-4272-b4f1-7e1ac8de154f)
**Predicted results**
Implement support ticket workflow and improve support

**Comment by Shih-Yu** [comment]
@MRTIBBETS  new form update in the works.

**Comment by FullStackTiger** [comment]
There is a new form.
![image.png](https://images.zenhubusercontent.com/616efed4bc03b82db7d9e3ae/449cabc5-b4be-4a00-927c-e13401459bc9)
