### ISSUE TITLE
Lens Integration Eng Design + Ticket Breakdown

### ISSUE THREAD

**Issue by pglowacky** [livepeer/studio#1044]
Based on this https://www.notion.so/livepeer/Lens-Protocol-Livepeer-SDK-Product-Scope-8c1de0cdf2394a88baf24653c8875037, write a document on the various engineering challenges with proposals on how to solve them.

**Comment by victorges** [comment]
https://www.notion.so/livepeer/Lens-Integration-e756c036e6c741de97d8e9ef1c351e84#90373644024348108d2852ecaa21aa6f
