### ISSUE TITLE
HLS playback of assets using playbackId

### ISSUE THREAD

**Issue by victorges** [livepeer/studio#1048]
Assets cannot be played back via HLS using their `playbackIds`. This means that we have an inconsistent experience between streams and assets, and also between assets own download URL (to get the MP4, which uses the playbackId) and playback URL (which uses an internal ID from a stream created to generate HLS playback).

This also creates undesired complexity in the NFTs that we want to mint with these assets. To support retrieving and playing back the asset from the livepeer.com platform, we cannot simply include the `playbackId` of the asset in the NFT. Instead, we also need to include this internal ID of the stream created for that asset, and the playback URL needs to be built as if it were a livestream recording and not an asset.

Although it'd be nice to have HLS playback URLs consistent between assets and streams, it is not the case right now. Our media server infrastructure might change drastically in the near future as well, and so we wanna add as little complexity as possible to that. So we will avoid serving assets HLS playlists from the same endpoint as streams (`/hls/[pid]/index.m3u8`) right now. Instead, we will create a new route for the VOD assets so you need to know if you have an asset or stream `playbackId` before creating a playback URL.

### Auth Webhook

This is to update the `authWebhook` to support asset playback routes. This hook is called by the broadcaster before every stream starts and before every recording is served, to authorize the operation (e.g. block suspended users) and also return any metadata that the broadcaster requires (e.g. stream profiles for /live/, or the session info for recordings). 

We would be adding support for a new kind of URL there, which would lookup for the asset given the `playbackId` in the URL, pick the `playbackRecordingId` from the asset payload and return the session information to the broadcaster.

Although this would work seemlessly from the outside, it is more complex to implement and would require touching and iterating on some code that hasn't changed much in a few months. It would also require changing the recording broadcaster code for handling the new URL for asset playback (even if everything after that is the same, just using the same handler as the sessions), and adding a new traefik route in our cluster ingress.

This leads us to the second path:

### Redirect

This is to create some API or service that handles whatever URL we want to playback an asset (e.g. `/asset/[pid]/index.m3u8`), but instead of serving it directly, it simply looks up for the asset with the corresponding playbackId in the database and responds with a **redirect** to the recording playback URL. This should work in most HLS players since it is apparently a pretty standard practice in the video industry to use redirects in HLS playlists. 

This service handling the asset playback URL might as well be the API itself. The logic here would be pretty simple, likely smaller than the change that would be needed for the `authWebhook` change. We would not need any change on the broadcaster, but we would still need to add routes in our infra. 

So this is the currently proposed approach.

## Pending decisions
 - We need to decide if we can use an HLS URL like `/asset/[pid]/index.m3u8` or if that would create too many issues with the existing route that we have for accessing the raw asset files, like the `downloadUrl` which is currently like this `/asset/[pid]/video`. It might be the case that we need to use a different root segment or the path. This shouldn't add much complexity to the implementation anyway.

## Product Questions

1) How much effort do we estimate to investigate and fix?

3-5 days of work to include proper testing.

2) What's the risk if we don't implement it, how does the customer experience suffer, etc.

This is not exactly a bug, but if we were to use the same rating I'd say it's a [P2](https://www.notion.so/livepeer/Bug-Prioritization-Methodology-DRAFT-e1e43628698740b8966c09b23b5d73e6) (high impact, low sev).

If we don't implement this before launching the Lens integration SDK, we might end up with several NFTs created that have references to internal IDs in our API, specifically the internal stream created for preparing the assets.

NFTs are immutable, so those legacy references will stay there forever, and so this might create a tech debt hard to get rid of. There is also a risk that other developers build things on top of these internal IDs, and then we are not even able to remove them from the new NFTs anymore. 

So the impact is high because it affects all assets and it leaks complexity into all the NFTs/Lens posts created with Livepeer videos. Would be theoretically low severity *right now* because it does not affect the core functioning of the video minting / playback. It can become higher severity in the future as the tech debt affects our ability to iterate on our service, like for example evolving from this internal stream recordings to provide HLS playback, doing a mist-first approach instead.

**Comment by pglowacky** [comment]
Not blocking the Lens integration, moving back to the backlog. However, will clarify the API structure.

**Comment by pglowacky** [comment]
This functionality is out of the box with the pipeline work by DMS, so Studio won't need to handle this
