### ISSUE TITLE
Investigate: PlayDJ VOD failed to upload

### ISSUE THREAD

**Issue by pglowacky** [livepeer/studio#1054]
> But essentially I attempted to upload an mp4 file three times using the Upload api endpoint. There's a few things that came out of this that would be cool to discuss:
> 
> 1) they all failed. Which is fine, I'm sure I probably just need to configure the api call differently. But one problem is, the second call to upload the file to the given URL, is returning 200 successful. I'm assuming this is async, but then there's no way to check or be notified if the upload actually succeeded. Webhooks would be ideal here.
> 
> 2) I'm not actually sure why they failed? There's no error messages in the GUI or in the Asset List api response. So if you could shed some light here please
> 
> 3) the GUI that shows the assets, doesn't have any actionable for me, I can't click on the asset to do anything, there's no status to say it failed etc.

**Comment by victorges** [comment]
Getting ahead on some of the replies quickly here:
> 1. they all failed. Which is fine, I'm sure I probably just need to configure the api call differently. But one problem is, the second call to upload the file to the given URL, is returning 200 successful. I'm assuming this is async, but then there's no way to check or be notified if the upload actually succeeded. Webhooks would be ideal here.

To check the result of processing an upload asset, they need to check upon the `asset` and `task` objects returned by the `/request-upload` API that they already have to call before uploading a file. That API responds with the URL to upload and the pending `asset` and `task` objects. Maybe this function can serve as a good minimal example on how this should be done: https://github.com/livepeer/video-nft/blob/4e24bd46a884f7a0c23fe23b233cfd0c9a3bafad/src/minter.ts#L319

If they are able to do something like that on the code, I'd say that it's probably simpler and they wouldn't need webhooks. I've seen several developers confused about this though, so we do need to consider how to improve this API, or at least the documentation about it to make this clearer.

> 2. I'm not actually sure why they failed? There's no error messages in the GUI or in the Asset List api response. So if you could shed some light here please

From the `task` object mentioned above they will be able to see why it failed. They can just `GET /api/task/{taskId}` to monitor the progress of the asset processing (`{.status.progress}`) and then check any output error in the end (`{.status.error}`).

> 3. the GUI that shows the assets, doesn't have any actionable for me, I can't click on the asset to do anything, there's no status to say it failed etc.

I guess we need to add that to the new dashboard requirements? Some form of error handling and troubleshooting.
