### ISSUE TITLE
Return all ingest and playback base URLs

### ISSUE THREAD

**Issue by wohlner** [livepeer/studio#107]
**Problem:** 
API users are confused when the geo-located ingest and playback base URL changes overtime. 

**Solution:**
Return all ingest and playback base URLs. By calling https://livepeer.com/api/ingest, you should get results like this:

```
[
  {
    ingest: "rtmp://{region-0}-rtmp.livepeer.com/live",
    playback: "https://{region-0}-cdn.livepeer.com/hls"
  },
 {
    ingest: "rtmp://{region-1}-rtmp.livepeer.com/live",
    playback: "https://{region-1}-cdn.livepeer.com/hls"
  },
 {
    ingest: "rtmp://{region-2}-rtmp.livepeer.com/live",
    playback: "https://{region-2}-cdn.livepeer.com/hls"
  }
];
```

**Notes:**
The ingest and playback base URLs should be grouped as pairs to help emphasize to the user that they are related. The documentation will also specify that you cannot use a region-1 ingest URL with a region-2 playback URL.

**Comment by darkdarkdragon** [comment]
@wohlner 
no need to do anything here. Request
https://livepeer.com/api/ingest?first=false
will return
```json
[
   {
      "ingest":"rtmp://fra-rtmp.livepeer.com/live",
      "playback":"https://fra-cdn.livepeer.com/hls",
      "base":"https://fra-cdn.livepeer.com"
   },
   {
      "ingest":"rtmp://mdw-rtmp.livepeer.com/live",
      "playback":"https://mdw-cdn.livepeer.com/hls",
      "base":"https://mdw-cdn.livepeer.com"
   }
]
```

**Comment by wohlner** [comment]
amazing @darkdarkdragon, this is so helpful. Can this be used to unblock https://github.com/livepeer/livepeer-com/issues/108? cc: @ya7ya

**Comment by wohlner** [comment]
Nevermind, I just saw Ivan's comment in discord
