### ISSUE TITLE
Session table broken on stream page in livepeer.com dashboard

### ISSUE THREAD

**Issue by wohlner** [livepeer/studio#110]
**Problem:**
The table looks broken. Also, we no longer need a recording URL column. See below.

**Solution**
Remove the table for now.

![Screen Shot 2020-10-06 at 10.22.08 AM.png](https://images.zenhubusercontent.com/5d51866c4b419616253bda2e/9ea19458-45b3-420c-b92f-963ac60fbeff)

**Comment by adamsoffer** [comment]
This is now hidden.
