### ISSUE TITLE
Automated Billing Pre-launch Tweaks

### ISSUE THREAD

**Issue by wohlner** [livepeer/studio#111]
1. On /app/user/plans and /pricing, change the row order top to bottom to: Transcoding, Recording Storage, Streaming
2. In the pricing chart, on the Recording Storage row for Personal add "None"
3. In the pricing chart, on the Streaming row for Personal, change "Up to 10 concurrent viewers" to "Up to 10 concurrent viewers / account". The per account is important.
4. In the pricing chart, on the Transcoding and Streaming rows for Pro, change "$0.005" to " $0.005 USD" and "$0.01" to "$0.01 USD" respectively.
5. When I create a new account, verify, navigate back to the tab telling me to check my email /app/user/verify, click "home" (the livepeer icon in the upper left corner), and then click the dashboard button, I don't go to /app/user/ but incorrectly to /app/user/verify.
6. The sessions table is all messed up. Remove it. The bug is in prod too. [Already ticketed](https://app.zenhub.com/workspaces/video-user-team-5dd2c75e4ee08500015994d7/issues/livepeer/livepeer-com/110)

And of course, we need migration plan for existing users to move to the Personal Tier.

**Comment by adamsoffer** [comment]
Thanks @wohlner. Will work through these tweaks today.

**Comment by adamsoffer** [comment]
> When I create a new account, verify, navigate back to the tab telling me to check my email /app/user/verify, click "home" (the livepeer icon in the upper left corner, and then click the dashboard button, I don't go to /app/user/ but incorrectly to /app/user/verify.

@wohlner this is intended behavior implemented by @iameli since we don't want a user accessing the dashboard and streaming until they verify their account, so we redirect them to the verification page until they do. Perhaps we should remove the link to the dashboard from the nav _until a user verifies their email_ to avoid confusion. Thoughts?

**Comment by wohlner** [comment]
Sorry, just saw this notification. @adamsoffer I agree, I don't want the user accessing the dashboard and streaming until they verify their account. But what if they verify and navigate back to the tab that was already open to /app/user/verify (not the tab that opens after they click verify in the email)? At least when they refresh that original tab, they should be able to navigate to the dashboard or be redirected to /app/user/. 

What do you think? This isn't a dealbreaker for launching automated billing. Just a lil I noticed when testing.
