### ISSUE TITLE
Blog spacing livepeer.studio

### ISSUE THREAD

**Issue by swgeeLP** [livepeer/studio#1130]
On [livepeer.studio](livepeer.studio), can we add the option to pages/blogs (specifically the later) to change the spacing between paragraphs?

Currently it's only [like this](https://cdn.discordapp.com/attachments/989261309713457232/990999240090189834/unknown.png)... and we'd like the option to do [this](https://cdn.discordapp.com/attachments/989261309713457232/990999297141145661/unknown.png). Thanks!

**Comment by 0xcadams** [comment]
@swgeeLP found a solution to this - `SHIFT+ENTER`
