### ISSUE TITLE
Allow .MOV files to be uploaded using On Demand API

### ISSUE THREAD

**Issue by pglowacky** [livepeer/studio#1139]

**Comment by iameli** [comment]
I think this one will happen for "free" once we move to a Catalyst-based VoD backend

**Comment by pglowacky** [comment]
@iameli What's the timeline for the Catalyst-based VOD backend?

**Comment by pglowacky** [comment]
Closing since this work should live on the Catalyst side and supporting .mov in our current infrastructure would require a major refactor cc @victorges @gioelecerati
