### ISSUE TITLE
On Demand SDK (super-ticket)

### ISSUE THREAD

**Issue by pglowacky** [livepeer/studio#1141]
- Document proposal for On Demand / VOD SDK design based on [these requirements](https://www.notion.so/livepeer/User-Stories-Requirements-On-Demand-IN-PROGRESS-2c5516e49faf4f419962c63f0249dce1#3b02955261f8452994467b996cc51b9f)
- Send to Paige to finalized and discuss

**Comment by victorges** [comment]
Consider having the SDK under https://www.npmjs.com/package/@livepeer/sdk
