### ISSUE TITLE
Simpler webhooks for VOD

### ISSUE THREAD

**Issue by victorges** [livepeer/studio#1148]
- rename task.created -> task.started (or spawned)
 - task.status -> task.updated; asset.status -> asset.updated
 - New webhooks:
   - asset.error
   - asset.ready
   - asset.deleted

**Comment by pglowacky** [comment]
Flagging conversation still happening here about the changes to webhooks. Will clarify this ticket by EOD 7/20 or create new ticket https://www.notion.so/livepeer/User-Stories-Requirements-On-Demand-IN-PROGRESS-2c5516e49faf4f419962c63f0249dce1#aef60862ba79476ea4043b26214cc8bf

**Comment by pglowacky** [comment]
Finalized:

As a Web3 developer, building a creator platform

I want to surface the progress of video uploads to users 

So that they have visibility into what’s being uploaded, the progress, and any errors

Functional requirements:

- Should allow users to understand the status of tasks
    - `task.spawned`— An upload task has been created
    - `task.updated` — Indicates that the status of the task has changed. Payload will indicate the status of the task
    - `task.succeeded`— An upload task status is `ready`
    - `task.failed` — An upload task has errored
- Should allow users to understand the status of assets
    - `asset.created` — An asset has been created after upload is complete
    - `asset.updated` — An asset has been updated (metadata has been updated, renamed)
    - `asset.failed` — An error has occurred with an asset
    - `asset.ready`-- An asset is ready, with no errors, and is ready to be played
    - `asset.deleted` — An asset has been deleted

**Comment by victorges** [comment]
Should consider making it `asset.failed` instead of `asset.error`, just realized that the failure status in case of assets is also `failed` (not `error`). Good that they are both consistent (assets and tasks), we should probably keep the webhooks consistent as well.

**Comment by pglowacky** [comment]
Agree, keeps things consistent. @gioelecerati I've changed the above to reflect this suggestion.

**Comment by victorges** [comment]
Another change: `task.succeeded` should be `task.completed` for consistency with the task status. We can rename both to `suceeded` later since that's a better term, but let's keep it consistent there as well.
