### ISSUE TITLE
Document new VOD API endpoints

### ISSUE THREAD

**Issue by victorges** [livepeer/studio#1150]
- document PATCH /asset/:id -d {"storage": {"ipfs": {}}
  - document `asset.meta` field (maybe make it queryable)
  - document VOD webhooks
  - remove current `/export` docs

 lowest pri:
  - document /export as a "custom URL"-only thing

**Comment by pglowacky** [comment]
In addition, the API reference for VOD needs to be updated:
- Remove import
- clarify export

**Comment by Shih-Yu** [comment]
- document PATCH /asset/:id -d {"storage": {"ipfs": {}} -> https://github.com/livepeer/studio/pull/1161
- document VOD webhooks - need to make storage optional (similar to #1161)

**Comment by Shih-Yu** [comment]
@victorges added additional information on the default metadata fields of Livepeer Studio
https://github.com/livepeer/livepeer-studio-docs/commit/c07312fd08d43ef507431e4074d9d2ba48eb95f3

**Comment by pglowacky** [comment]
Is this done?

**Comment by Shih-Yu** [comment]
Yes, the document for it is here: https://docs.livepeer.studio/references/vod/patch
