### ISSUE TITLE
Dogfood: VOD 

### ISSUE THREAD

**Issue by pglowacky** [livepeer/studio#1156]
Please go through the VOD API and ensure that:

1. Calls and responses make sense. Is there anything confusing about how the calls are formatted or information in the responses that are unclear?
2. Does everything function the way it's supposed to? 
3. Is the documentation clear? Could we make it easier to use/understand? 

Please make tickets with any items that need to be addressed

**Comment by Shih-Yu** [comment]
`Update VOD` issue found, could not update each field separate and must include `storage`- fixed: https://github.com/livepeer/studio/issues/1172

**Comment by Shih-Yu** [comment]
`storage` object was difficult to understand in VOD response, issue fixed: https://github.com/livepeer/studio/issues/1166

**Comment by Shih-Yu** [comment]
VOD webhooks were not working since they required a `streamId` to be present- fixed: https://github.com/livepeer/studio/pull/1161

**Comment by Shih-Yu** [comment]
Updating meta on asset has a bug --> https://github.com/livepeer/studio/issues/1229

**Comment by victorges** [comment]
Only missing viewership dogfooding now.
