### ISSUE TITLE
Bug: Assets uploaded with subtitle tracks fail

### ISSUE THREAD

**Issue by pglowacky** [livepeer/studio#1157]
Reported by Lenstube that: https://livepeercdn.com/asset/48eeigdrovj7norx/ video is not found.

This was due to the processing of the asset failing due to having a `data` track, which we don't support 

Expected behavior:

As long as assets have a video and audio track, they should succeed. Any additional fields should be ignored rather than failing to process.

**Comment by Shih-Yu** [comment]
Lenstube provided another URL [https://arweave.net/KUdQdfbKTHPZ0hhsXx3LxcMBM_z_85X6ItWIy59lzbI](https://arweave.net/KUdQdfbKTHPZ0hhsXx3LxcMBM_z_85X6ItWIy59lzbI) which also has similar issue
```bash
Stream #0:2[0x3](eng): Data: none (tmcd / 0x64636D74)
    Metadata:
      creation_time   : 2022-07-03T17:51:21.000000Z
      handler_name    : TimeCodeHandler
      timecode        : 01:00:00;00
Unsupported codec with id 0 for input stream 2
```

**Comment by victorges** [comment]
https://github.com/livepeer/task-runner/blob/7a6cf603311a7d37aa06b8992107450daa9674e6/task/probe.go#L125-L127

**Comment by pglowacky** [comment]
This is fine to prioritize if this is a _very_ quick change, less than half a day. If it's a change that is even a bit complicated, I vote we move on since this will be covered by the VOD pipeline work by DMS
