### ISSUE TITLE
Document `request-upload` response 

### ISSUE THREAD

**Issue by pglowacky** [livepeer/studio#1158]
Following up on this: https://github.com/livepeer/studio/issues/1126

**Comment by Shih-Yu** [comment]
Made changes to the docs --> https://github.com/livepeer/livepeer-studio-docs/pull/144

Preview:  https://livepeer-studio-docs-git-sh-docapivod-livepeer.vercel.app/guides/on-demand#response-5

**Comment by victorges** [comment]
We might want something very similar to this: https://docs.mux.com/guides/video/upload-files-directly
