### ISSUE TITLE
Add retry logic to upload and transcode errors

### ISSUE THREAD

**Issue by pglowacky** [livepeer/studio#1164]

**Comment by pglowacky** [comment]
Doc created with errors [here](https://docs.google.com/spreadsheets/d/1i9o8B3HpuWvFzRRDwIjiSXU1ghmvX2OTIFSZ5wLyLII/edit#gid=0) needs @victorges and @gioelecerati 's input

**Comment by pglowacky** [comment]
@victorges @thomshutt I think we decided that retry logic should be on the DMS side, right? How can we help with handoff here?

**Comment by victorges** [comment]
@pglowacky retry logic will be in Studio! DMS will only take 1 task at a time with no strict reliability of guarantees like retries. That will be continue to be handled by task-runner through RabbitMQ.
