### ISSUE TITLE
Allow users to understand the health of `playback.user.new` webhook

### ISSUE THREAD

**Issue by pglowacky** [livepeer/studio#1171]
As a Web3 developer, building a creator application that utilizes token gating
I need to know whether the `playback.user.new` webhook is healthy and if it's not, what the error message is
So that I understand whether or not my stream is working and if its not, why not. 

This issue currently blocks more users from using and testing the token gating functionality

From Victor:

> Right now users have to blindly try and either get playback "just working" or "not working at all" with no error message to know what's wrong
maybe the account confusion started from that, but not sure
hans is having similar issues
from that other issue that shih-yu opened
he has a webhook calling https://streambot.vercel.app/api/webhooks/livepeer which just returns a 500
meaning playback is broken. but mist only returns "stream open failed". it doesn't say what's wrong (and that's better, we shouldn't be leaking the internal response to any user trying to playback)
if we showed that the webhook was failing tho (and the response we got), users could iterate on it themselves

**Comment by Shih-Yu** [comment]
Currently, the dashboard does show that the token gating webhook has a status `Idle` but even if the webhook is `Healthy`, still shows `Idle`
![Screen Shot 2022-07-20 at 2 41 33 PM](https://user-images.githubusercontent.com/53620329/180067866-725a2871-3b3f-4bd8-9da0-506e51f4cb5e.png)
