### ISSUE TITLE
More mp4 codec support + more CDN regions (Asia)

### ISSUE THREAD

**Issue by Shih-Yu** [livepeer/studio#1190]
**What's the problem? (required)** Describe the problem or need in exactly 1
sentence. Ex. "I'm unable to [...]", or "I am confused by [...]"

Sasi from Lenstube: 
- some of the videos that uploaded using URL is failed.  Currently only allowing .mp4 videos to upload, it might failed because it was not H264 , im not sure how many other codecs available in mp4.
- The video served from livepeercdn url takes long to load in client (atleast for me from India)
- Only concern for me is, uploads without any failure and seemless playback via CDN thats it.

**What's the current behavior? (required)** A clear and concise description of
the current behavior of the DApp or package (or lack thereof).

- Upload to Arweave and ingesting URL to Livepeer fails at times due to other formats other than H.264 + AAC
- Experiencing long load time from serving Livepeer cdn URL

**Comment by victorges** [comment]
- slow loading in client is likely cause of using download URL, not playback URL. should be instructed about using an HLS player like lvpr.tv
 - the error might not really be about codecs. nevertheless, we will fix both the codecs and this issue that we think is happening here in less than 1 month (with migration to Catalyst VOD)
