### ISSUE TITLE
Dashboard: Metadata is not what it seems

### ISSUE THREAD

**Issue by pglowacky** [livepeer/studio#1212]
https://images.zenhubusercontent.com/283575154/18090f96-9610-474d-b3b9-d4c1b50bc906/2022_08_23_09_30_20.mp4

Using Brave and Chrome, I uploaded a video and attempted to edit the metadata. Currently, the dashboard only allows you to replace the entire metadata (so you can't retain fields like the CID). This prevents me from adding in additional metadata without replacing all of the metaddata. 

As a user, I'd expect the text field to allow me to edit the standard metadata and add in additional fields, rather than deleting all of the standard metadata

**Comment by pglowacky** [comment]
closing in favor of https://app.zenhub.com/workspaces/studio-62e817e78dcba15ddb23d5ad/issues/livepeer/studio/1229

**Comment by gioelecerati** [comment]
I think this and https://app.zenhub.com/workspaces/studio-62e817e78dcba15ddb23d5ad/issues/livepeer/studio/1229 are two separate issues. This one is referring to the `nftMetadata` field, the other one to the `meta` field of the asset, which is a custom field for user arbitrary data!

**Comment by Shih-Yu** [comment]
Once you add the meta with the format, it works
https://images.zenhubusercontent.com/283575154/4dd30007-5ff7-4f2f-bb08-5421948cfb5b/screen_recording_2022_09_15_at_8_48_59_am.mov

**Comment by adamsoffer** [comment]
@pglowacky that's actually placeholder text in that textarea hence why you can't edit it. I'm going to design a better interaction for entering meta data so it's easier and more obvious how to enter this data. In the mean time, LIke Shih-Yu mentioned, once you add meta data you can edit it.

**Comment by pglowacky** [comment]
Closing since we've removed this feature from the dashboard
