### ISSUE TITLE
Replace player in Livepeer Studio Dashboard with Livepeer Player

### ISSUE THREAD

**Issue by adamsoffer** [livepeer/studio#1227]

**Comment by pglowacky** [comment]
@adamsoffer Should we have some copy and paste code for the player in the dashboard too? I could throw together wireframes....

**Comment by adamsoffer** [comment]
@pglowacky That would be a nice feature. Let's open an issue for this. I can design it. I suggest we design the embed experience similar to how YouTube does. We can add a share button below the player that opens a modal and inside the modal they can optionally copy a share url or click embed which opens a modal similar to this ![CleanShot 2022-09-05 at 10.45.28@2x.png](https://images.zenhubusercontent.com/5d377853504de01743fe7d98/cd2555dc-360c-4cbe-814e-dcbac334597e)

**Comment by pglowacky** [comment]
Will close issue #973 and #1239
