### ISSUE TITLE
New VOD webhooks not currently documented

### ISSUE THREAD

**Issue by pglowacky** [livepeer/studio#1230]
Webhooks listed [here](https://app.zenhub.com/workspaces/studio-62e817e78dcba15ddb23d5ad/issues/livepeer/studio/1148) are in the dashboard but are not listed [here](https://docs.livepeer.studio/guides/listen-for-webhooks)

**Comment by gioelecerati** [comment]
Aren't the doc for them present into https://github.com/livepeer/livepeer-studio-docs/pull/157 ? I remember detaching the docs from the studio pr

**Comment by Shih-Yu** [comment]
https://github.com/livepeer/livepeer-studio-docs/pull/157#issuecomment-1195565958

**Comment by Shih-Yu** [comment]
Created a pr for the new docs site added @gioelecerati and @pglowacky for review
https://github.com/livepeer/livepeer-studio-docs/pull/185

**Comment by Shih-Yu** [comment]
Closing pr, Gioele approved and it has been merged
https://github.com/livepeer/livepeer-studio-docs/pull/185
