### ISSUE TITLE
Demo by 8/31

### ISSUE THREAD

**Issue by pglowacky** [livepeer/studio#1234]
- Demo of the API 
- Demo of the SDK

https://discord.com/channels/423160867534929930/993331529495351357/1012092688713134110

**Comment by 0xcadams** [comment]
Is this done?

**Comment by Shih-Yu** [comment]
@0xcadams, yes - here is the recording of it https://discord.com/channels/423160867534929930/446434320777871380/1014588901039554580
Will close this.
