### ISSUE TITLE
Broken link to Sample Applications

### ISSUE THREAD

**Issue by pglowacky** [livepeer/studio#1251]
![image.png](https://images.zenhubusercontent.com/602ea479bcf4ef10a9aace61/47d86998-3c12-4210-9b10-460de8d92068)

Should go to: https://docs.livepeer.studio/reference/examples

**Comment by pglowacky** [comment]
This too! 

![image](https://user-images.githubusercontent.com/79172645/188695239-4458c67a-6658-4c7b-85e4-09e0a1709955.png)

Getting Started Tutorial also 404s

**Comment by swgeeLP** [comment]
This one too 
<img width="150" alt="image" src="https://user-images.githubusercontent.com/108287299/188707722-2c70bae5-ee51-4723-9adc-40a7ddb33993.png">

**Comment by clacladev** [comment]
These issues were addressed as part of https://github.com/livepeer/studio/pull/1266
PR #1226
