### ISSUE TITLE
Add upload date to IPFS integration component

### ISSUE THREAD

**Issue by pglowacky** [livepeer/studio#1253]
Currently, the copy under "Decentralized Storage Providers" is static, which can be confusing if you've already stored an asset to IPFS. If an action was taken to pin an asset IPFS we should include an upload date so this is more clear.

**Comment by adamsoffer** [comment]
Updated component design with upload date:
<img width="631" alt="CleanShot 2022-09-11 at 23 11 07@2x" src="https://user-images.githubusercontent.com/555740/189567198-c22cd465-a262-45a1-8a54-12f9104aef98.png">

**Comment by pglowacky** [comment]
Looks good to me! cc @hthillman

**Comment by victorges** [comment]
Can fetch the task and show the `task.status.updatedAt`
