### ISSUE TITLE
Dashboard website UX issues

### ISSUE THREAD

**Issue by swgeeLP** [livepeer/studio#1255]
A few issues, mostly small, often persnickety branding/writing feedback from the words guy, in no particular order:

- On https://livepeer.studio/dashboard, under the "Create your own live stream", where it says "like OBS Studio or streamlabs. Here’s how.", there should be a colon after "here's how:"
- On all dashboard pages, links/button use blue text, but so do some of the headings. Can we use different colors to make it clear what’s clickable and what’s not? (If the brand guide / design allows it.)
- On https://livepeer.studio/dashboard/assets, the "Learn more -->" button leads to a 404.
- Same thing for the other Docs links on the main dashboard page, 
- On https://livepeer.studio/dashboard/assets, "Upload your first Video on Demand asset" should become "Upload your first On Demand asset", to align with the feature's brand.
- On https://livepeer.studio/dashboard/assets, "Video on Demand" shouldn't be capitalized, because it's describing the On Demand feature, which _is_ capitalized because it's a branded feature term. The same is true for video on demand vs On Demand elsewhere on the dashboard or docs.

**Comment by clacladev** [comment]
@adamsoffer Investigating the "Learn more" link being broken, I discovered that **all** links to documentation are broken.
So I mapped them all and I want to have confirmation that the new links are the best resource to reference.

Home page: Getting started tutorial
From https://docs.livepeer.studio/guides/livestreaming/ 
To https://docs.livepeer.studio/guides/live/create-a-livestream

Home page: Build with the API, Explore the API
From https://docs.livepeer.studio/references
To https://docs.livepeer.studio/category/api

Home page: Create your own app, Clone and create
From https://docs.livepeer.studio/guides/sampleslib
To https://docs.livepeer.studio/category/api

Home page: Create your first stream, learn more
From https://docs.livepeer.studio/guides 
To https://docs.livepeer.studio/guides/live/create-a-livestream 

Asset page: learn more
From https://docs.livepeer.studio/docs/api-reference/vod/import
To https://docs.livepeer.studio/category/on-demand 

Streams page: learn more
From https://docs.livepeer.studio/guides
To https://docs.livepeer.studio/category/live 

Stream session: No session, learn more
From https://docs.livepeer.studio/references/session/
To https://docs.livepeer.studio/reference/api/get-session

API Keys: Learn more
From https://docs.livepeer.studio/references
To https://docs.livepeer.studio/category/api

API Keys: Create key, Allow CORS access 
From https://docs.livepeer.studio/guides/livestreaming/api-key#cors
To https://docs.livepeer.studio/quickstart/#create-api-key

**Comment by adamsoffer** [comment]
@clacladev Thanks for mapping these out. Looks good. Let me know if you find another more broken links to the docs.
