### ISSUE TITLE
Multistream Idle tag overlapping

### ISSUE THREAD

**Issue by Shih-Yu** [livepeer/studio#1272]
**Describe the bug (required)** A clear and concise description of what the bug
is.

- When creating a new multistream, the idle tag shows up in the input form

**Expected behavior (required)** A clear and concise description of what you
expected to happen.

- Not to have the idle tag in the name input field

**To Reproduce (required)** Steps to reproduce the behavior:

1. Go to dashboard
2. Go to existing stream
3. Click on `+ Create` button for multistream

**Device (required):**

- Device: Mackbook Pro
- OS: Monterey
- Browser  Chrome, Safari
- Version 104.0.5112.102, 15.6.1

**Screenshots (optional)** If applicable, add screenshots to help explain your
problem.
![Screen Shot 2022-09-13 at 11 24 38 AM](https://user-images.githubusercontent.com/53620329/189959083-dfc52276-d682-48b1-bd5b-f42b5b0277f9.png)

**Comment by clacladev** [comment]
This bug can be closed. It has been solved part of some previous work I've done.
Here you can see that the Idle tag is below the Multistream popup now.
![Screenshot 2022-12-21 at 16.22.33.png](https://images.zenhubusercontent.com/63048adb4bfb02a9a4a39ef6/0d14b417-110d-4607-9bc0-f7afddf12338)
