### ISSUE TITLE
Embeddable player in Dashboard

### ISSUE THREAD

**Issue by pglowacky** [livepeer/studio#1282]
Feedback on On Demand. Context: https://app.zenhub.com/workspaces/studio-62e817e78dcba15ddb23d5ad/issues/livepeer/studio/1227

@adamsoffer can you update this ticket on any progress related to the embeddable player code in the dashboard? Curious how far we got.

**Comment by adamsoffer** [comment]
@pglowacky[ here's the proposed design](https://www.figma.com/file/o0lkaZxamhUfG6eqSglhPO/Livepeer-Studio-Dashboard?node-id=759%3A4580
). Can you leave feedback in the comments if you have any? We can begin implementation this week. 



Preview:
<img width="456" alt="CleanShot 2022-09-19 at 10 46 19@2x" src="https://user-images.githubusercontent.com/555740/191045642-4177881a-af2d-494e-b501-199a9afd7920.png">

<img width="460" alt="CleanShot 2022-09-19 at 21 20 19@2x" src="https://user-images.githubusercontent.com/555740/191146542-128528b4-6e93-45d4-90b9-4602302853bf.png">

**Comment by victorges** [comment]
FTR we can reuse the lvpr.tv player from
https://github.com/livepeer/player

Should update it to use the SDK player as well

**Comment by victorges** [comment]
FTR we can reuse the lvpr.tv player from
https://github.com/livepeer/player

Should update it to use the SDK player as well

**Comment by adamsoffer** [comment]
👆 deleted a duplicate comment

**Comment by victorges** [comment]
btw we also have docs on embedding the lvpr.tv! might need to update that after migrating it to the SDK player (ideally not breaking the interface tho, just in case users are already using it in the wild):
https://docs.livepeer.studio/guides/playback-a-video-stream#video-player

Will want to at least mention that you can just copy the embeddable code for a given video from the dashboard (although users building a programatic embedding might not go through that flow anyway)

**Comment by clacladev** [comment]
It seems clear enough but I have a couple of extra questions.

1. @victorges @adamsoffer the code that can be copied and pasted is the one [linked here](https://docs.livepeer.studio/guides/playback-a-video-stream#example-code) right?

2. @adamsoffer in the design for this Embed feature, there is also a Copy link and Download button. Are these features for another time, or are we including them already?

3. Is this only for On Demand? Not for Streams, right?

**Comment by adamsoffer** [comment]
1. Yup that's right 👍 
2. Yes let's include the "copy link" and "download" call to actions from the design as well
3. Yes, let's add this to the stream detail view as well (minus the download button since there's nothing to download when live).

**Comment by pglowacky** [comment]
The design looks great!

**Comment by clacladev** [comment]
Hello all! There is a PR out for this issue. There are a few things, described in the PR, that I need confirmation of.
If you want to take a look, here it is
https://github.com/livepeer/studio/pull/1295
