### ISSUE TITLE
Fix React Native Demo 403 error encountered when running app locally

### ISSUE THREAD

**Issue by adamsoffer** [livepeer/studio#1290]
**Problem**
A user reported a 403 error when attempting to run this example app locally

**Potential Solution**
Update old api endpoints from `livepeer.com/api` to `livepeer.studio/api` as and playback urls from `cdn.livepeer.com` to `livepeercdn.com`

**Comment by jrmaktub** [comment]
Hello. Any progress on this?  Thanks

**Comment by clacladev** [comment]
I am going to investigate this bug in the next couple of days. Follow the issue for updates

**Comment by jrmaktub** [comment]
Help please

**Comment by clacladev** [comment]
Hello @jrmaktub I was wondering if you could test the fixes, before merging them.
Can you checkout [this branch](https://github.com/livepeer/livepeer-demo-react-native/pull/5) and try to run it and see if you still receive the 403 error?


Thanks a lot!
