### ISSUE TITLE
Design: Sample Application: Using SDK for NFT Minting

### ISSUE THREAD

**Issue by pglowacky** [livepeer/studio#1298]
- Upload video assets, store assets at IPFS, edit the metadata according to ERC-721 standards or Aptos metadata standards (TBD)
- Should allow users to mint without specifying a contract — minting to a common contract is okay for sample application purposes
- Should allow video minted to be played back using the Livepeer Player
- Should return a contract address and a Token ID (JSON metadata blob on IPFS)
- Should be on it’s own dedicated domain (optional)

![image.png](https://images.zenhubusercontent.com/602ea479bcf4ef10a9aace61/59b67cf0-6b7f-4a15-9f88-c9906afed329)

![image.png](https://images.zenhubusercontent.com/602ea479bcf4ef10a9aace61/acd76ea9-8558-43f4-b4bd-2fc65deb8b50)

**Comment by pglowacky** [comment]
@adamsoffer put together low fidelity wireframes, let's discuss if you'd like the sample app to function differently than how I've laid it out

**Comment by Shih-Yu** [comment]
I can add a NFT Minting SDK to the nav of the current sample app and have it direct to a page that looks like draft

**Comment by pglowacky** [comment]
@Shih-Yu I'm thinking that this should be stand-alone so Aptos can send it to their developers and we can link to it from the Sample App. WDYT?

**Comment by Shih-Yu** [comment]
Was thinking about that and agree, I can add one to the sample app later that is more generic.
