### ISSUE TITLE
Access control on dashboard

### ISSUE THREAD

**Issue by pglowacky** [livepeer/studio#1300]
[Requirements to be written] 

https://www.notion.so/livepeer/Signing-Keys-for-Access-Control-8879f96a5aaf409eb4042acc281f5caa

**Comment by pglowacky** [comment]
Signing Keys:
![image.png](https://images.zenhubusercontent.com/602ea479bcf4ef10a9aace61/b7409b6f-7905-4cbc-920e-0599806a5255)

Private Stream:
![image.png](https://images.zenhubusercontent.com/602ea479bcf4ef10a9aace61/36d14199-cab3-43ee-b6ed-6308d362cce4)

Private asset:
![image.png](https://images.zenhubusercontent.com/602ea479bcf4ef10a9aace61/4d8cd9da-ec0c-4514-807d-5748cf4bac74)

**Comment by pglowacky** [comment]
Met with @gioelecerati + @adamsoffer and discussed what this functionality will look like in the dashboard. 

- Finalized naming: Product should be referred to as "Playback Policy" 
- There's no way for a user to use the dashboard alone to sign JWTs because of the nature of the key pairs which have a public and private key. Since Studio does not store the private key, it cannot sign a JWT on behalf of the user. We decided that we'd allow the users to set the playback policy for both livestreams and on demand assets in the dashboard, but would point them to documentation on actually performing the JWT signing. 
- Once an asset is signed, it is not viewable on the dashboard so any dashboard changes should include including some kind of error messaging on the player when a stream is private. 
- Currently the cache is 10 min to prevent Studio from being knocked over from requests from Catalyst. We're going to reduce this to 5 min for now and move some of this functionality off of Studio and onto Catalyst in future iterations to avoid having Catalyst make requests of Studio. This cache means that if you change a video that is in progress and currently being viewed to have a playback policy of `JWT` it will take 10min for the viewers to stop seeing the video. 
- Adam has a good sense of where to take the designs next and we'll review them once completed.

**Comment by pglowacky** [comment]
@clacladev to tackle the FE work this week for just the signing keys. @adamsoffer to share the finalized designs.

**Comment by adamsoffer** [comment]
@pglowacky I just created a [separate issue](https://github.com/livepeer/studio/issues/1345) for implementing the signing key view.
