### ISSUE TITLE
Pending stream status in dashboard

### ISSUE THREAD

**Issue by Shih-Yu** [livepeer/studio#1312]
**Describe the bug (required)** A clear and concise description of what the bug
is.

- The status of stream in the dashboard displays `pending` even though it is active

-this happens when the stream becomes active but the .m3u8 is not ready yet. The frontend receive a 200 from the HLS thinking it's loaded correctly and does not retry to load it, but the actual manifest has this content:

`#EXTM3U
#EXT-X-ERROR: Stream open failed
#EXT-X-ENDLIST`
The player would need retry to load the playlist in this situation until the manifest is ready and correctly loaded 

**Expected behavior (required)** A clear and concise description of what you
expected to happen.

- The status should show `healthy` when the streaming is going

**To Reproduce (required)** Steps to reproduce the behavior:

1. Start a steam in OBS
2. Go to the stream dashboard
3. See error

**Device (required):**

- Device: MacBook Pro
- OS: Monetery
- Browser  Chrome, Safari
- Version [latest/latest]

**Screenshots (optional)** If applicable, add screenshots to help explain your
problem.

https://user-images.githubusercontent.com/53620329/192885521-c5a31e18-7fbe-4627-a52d-a9fd76be221d.mov

**Comment by 0xcadams** [comment]
This should be fixed in https://github.com/livepeer/livepeer.js/pull/42/commits/4ed6961daa433981dd3d79f3936063baee0884e5, will need to be added to studio once release

**Comment by Shih-Yu** [comment]
Closing this issue as it seems to be fixed
https://discord.com/channels/423160867534929930/1025115716044718242/1025505538072641566
