### ISSUE TITLE
Recorded streams not showing up

### ISSUE THREAD

**Issue by Shih-Yu** [livepeer/studio#1314]
**Describe the bug (required)** A clear and concise description of what the bug
is.

- Recorded livestreams not recording or processing correctly. Tom from Subb has his dashboard showing `processing` for the recorded streams. I get the duration, but not all recorded streams are showing, and also not provided with the recording URL.

**Expected behavior (required)** A clear and concise description of what you
expected to happen.

- When recording a live stream, after ~5 mins. the recorded stream should be available to view.

**To Reproduce (required)** Steps to reproduce the behavior:

1. Start stream in OBS
2. Go to Studio dashboard
3. Record live stream
4. Stop stream and wait for processing and see error

**Device (required):**

- Device:  MacBook Pro
- OS: Monterey
-Browser: Brave
- Version: Version 1.43.93 Chromium: 105.0.5195.127 (Official Build) (arm64)

**Screenshots (optional)** If applicable, add screenshots to help explain your
problem.

![Tom form Subb](https://cdn.discordapp.com/attachments/730147691698585660/1025032297075974235/unknown.png)

![Mine](https://cdn.discordapp.com/attachments/730147691698585660/1025047453508046938/Screen_Shot_2022-09-29_at_9.11.43_AM.png)

**Comment by yondonfu** [comment]
Keeping this open until the relevant fix is deployed.

**Comment by Shih-Yu** [comment]
Closing:
https://discord.com/channels/423160867534929930/1025115716044718242/1025505105283403797
