### ISSUE TITLE
Audio-only playback not working

### ISSUE THREAD

**Issue by Shih-Yu** [livepeer/studio#1318]
**Describe the bug (required)** A clear and concise description of what the bug
is.

- When using `https://livepeercdn.com/hls/{playbackId}/index.m3u8?video=false` this video is also showing.

**Expected behavior (required)** A clear and concise description of what you
expected to happen.

- Using the audio-only playback should only have the audio playing with a blank screen for live stream and assets

**To Reproduce (required)** Steps to reproduce the behavior:

1. Get the playback URL of a stream or asset
2. add `?video=false` to the end of the playbackURL
3. View the stream or asset and see the error

**Device (required):**

Device: MacBook Pro
OS: Monterey
Browser: Chrome
Version: Version 1.43.93 Chromium: 105.0.5195.127 (Official Build) (arm64)

**Screenshots (optional)** If applicable, add screenshots to help explain your
problem.

https://user-images.githubusercontent.com/53620329/193098423-8c6e247e-0490-477e-be8f-e5334d39e90b.mov

**Comment by iameli** [comment]
Fixed by https://github.com/livepeer/catalyst/commit/e67cc27f4fa39b5711abe7215f03554b7ecef280 and rolled to production :+1:
