### ISSUE TITLE
Implement signing key view

### ISSUE THREAD

**Issue by adamsoffer** [livepeer/studio#1345]
https://www.figma.com/file/o0lkaZxamhUfG6eqSglhPO/Livepeer-Studio-Dashboard?node-id=845%3A4956

**Comment by clacladev** [comment]
@adamsoffer the design makes total sense. I think I will add a Spinner next to the Generate button once pressed, waiting for API response, the I will show the actual keys.

**Comment by clacladev** [comment]
@adamsoffer I need to confirm a few things for the Empty state:
1. I am going to use the same design as the Empty API Keys screen
2. The text in the empty state should be `Signing keys allow you to add access control to streams and assets`, is it ok?
3. The Learn More link in the empty state, where should it point to? `https://docs.livepeer.studio/category/api` as for the Empty API Key screen?
