### ISSUE TITLE
Playback Policy Sample Application

### ISSUE THREAD

**Issue by pglowacky** [livepeer/studio#1352]
## Context

We're planning on launching Playback Policies (aka Access control aka token gating) by Friday, 10/28. Playback Policies allow users to set live streams (and soon VOD assets) to `public` or `JWT`. If `JWT` is selected, live streams will not playback from a standard playback URL and will require that a JWT be signed and appended to the end of the playback URL. PR for documentation is here: https://app.zenhub.com/workspaces/studio-62e817e78dcba15ddb23d5ad/issues/livepeer/livepeer-studio-docs/206

This feature was designed to be part of a token gating flow that:
1. End users are signing into the client with Web3 auth
2. End users attempting to view token gating content are verified on an ACL (could be Lit Protocol or standard backend ACL) 
3. If users is on ACL, client signs JWT, links user to the signed URL for viewing.

## Objective

Educate developers on how to use Playback Policies by creating a sample application and written tutorial. 

## Requirements

Sample application must include:
- Sign in with web3 auth (provider is your choice) 
- Connecting wallet address to an ACL
- ACL implementation (can be Lit Protocol or other provider, or standard backend ACL) 
- Using playback policies to allow to disallow a viewer

Written tutorial should include step-by-step instructions on how to perform the various integrations. 

cc @adamsoffer

**Comment by Shih-Yu** [comment]
[WIP]
https://github.com/livepeer/Playback-Policy-Sample-App
