### ISSUE TITLE
Delete old NFT Minting interface at .studio/mint-nft

### ISSUE THREAD

**Issue by pglowacky** [livepeer/studio#1381]
When we originally launched the NFT Minting SDK, we also built a sample application at .studio/mint-nft. Since relaunching the NFT minting SDK, we missed also updating this existing sample application. This experience should be rebuilt using the existing SDK. 

Additionally, because of some broken CSS the current sample application is hidden: 

![image.png](https://images.zenhubusercontent.com/602ea479bcf4ef10a9aace61/b9c5ab8e-9d8b-47bb-a2a1-9d6574df9e6c)

**Comment by clacladev** [comment]
@pglowacky @adamsoffer should I still go ahead and remove this NFT minting page, given we've stopped the new Minting project?

**Comment by adamsoffer** [comment]
Yeah, it should have been deleted along time ago. It looks bad and no one uses it!
