### ISSUE TITLE
Minor: Adjust padding so text isn't cut off

### ISSUE THREAD

**Issue by pglowacky** [livepeer/studio#1383]
"e.g. New key" in the text field is cut off slightly. 

![Screen Shot 2022-09-19 at 9.55.52 AM.png](https://images.zenhubusercontent.com/602ea479bcf4ef10a9aace61/95a0ca9d-95f1-46fa-93ac-f20489bdf29e)

**Comment by clacladev** [comment]
@pglowacky I looked into this and it appears that there is not any issue. 
This specific input field grows its height based on the font size. There is no constraint in term of vertical space.

Zooming in the text `e.g.` and looking at the tail of the `g`, you could see that the curve is smoothed. It's not a great job, it looks flattish, but it's there. If you look at the `e`, the bottom part has the same identical issue.

I checked the other input fields (e.g. Create stream) and they have all the same behaviour.

I played around with the aliasing and other settings, but it all seems normal. This is just a visual illusion.

I think this ticket should be closed.
