### ISSUE TITLE
Minor: Update language on dashboard upload modal to clarify what containers are accepted

### ISSUE THREAD

**Issue by pglowacky** [livepeer/studio#1384]
Currently, it's unclear what file types we accept. Update this modal to indicate that we support .mp4 files

![image.png](https://images.zenhubusercontent.com/602ea479bcf4ef10a9aace61/66bbc846-5883-420b-a217-412d19a3d4cb)

**Comment by pglowacky** [comment]
@clacladev supported file types are .mp4, .mov, .avi, .webm, .wmv, .mkv, .flv.

Can we add these in?

**Comment by clacladev** [comment]
@pglowacky yes I can do that
