### ISSUE TITLE
Test the player in a new react native application

### ISSUE THREAD

**Issue by 0xcadams** [livepeer/studio#1403]
- Needs definition of "testing" 
- Distribute testing app in testflight or firebase

**Comment by clacladev** [comment]
Livepeer.js RN feedback for @0xcadams 

- Getting started
    - In Step 1 I install `react-native-svg` following the instruction which installs 13.6.0, but expo complains when running the app that it’s incompatible and the version 13.4.0 should be installed. It still works, but do we want to address this issue?
    - In Step 3, I copy and paste the RN snippet but there is an error. It’s using <div> tags instead of <Text> components. The asset object should also be nullable `<Text>Asset: {asset?.name}</Text>` to avoid some RN error due to lifecycle
    - In Step 3, `const asset = useAsset(…)` should be a `const { data: asset } = useAsset(…)`
- Client page
    - Storage chapter for RN the text is a bit confusing, it’s not clear if it caches or not by default. The first and last sentence contradict each other.
- Player
    - Once after integrating the player it works!
    - But there are issues when going fullscreen and then rotating the device. The video freezes
    - Poster chapter for RN has the wrong line highlighted

**Comment by 0xcadams** [comment]
Followed up with https://github.com/livepeer/livepeer.js/issues/186 and added docs fixes for other points

**Comment by suhailkakar** [comment]
I was able to integrate @livepeer/react-native package without any issues 🎉 

The player was working fine but sometimes, when rotating the device, the video freezes (As mentioned by Claudio)
  
 @0xcadams Should I test other hooks such as `useCreateAsset`, `useStream`, or just the player component?
