### ISSUE TITLE
EVM-compatible Sample Application for Token Gating 

### ISSUE THREAD

**Issue by pglowacky** [livepeer/studio#1506]
using the Aptos Sample App, create a sample application that is EVM-compatible.

**Comment by pglowacky** [comment]
@adamsoffer Thoughts on which chain to use? Polygon?

**Comment by adamsoffer** [comment]
That works.

**Comment by suhailkakar** [comment]
Deployed version: https://livepeer-evm-tokengating.vercel.app/
GitHub Repo: https://github.com/suhailkakar/Livepeer-EVM-Tokengating

Users can authenticate with 
- Metamask 
- Coinbase Wallet 
- Wallet connect

Supported Chains 
- Ethereum 
   - Mainnet 
   - Goerli (Testnet)
- Polygon
   - Mainnet 
   - Mumbai (Testnet)
- Arbitrum
   - Mainnet 
   - Arbitrum Testnet
- Optimism
