### ISSUE TITLE
Collect debugging info about Mist RTMP error with react native lib

### ISSUE THREAD

**Issue by victorges** [livepeer/studio#1533]

**Comment by clacladev** [comment]
Here a document documenting the entirety of the issue and https://www.notion.so/livepeer/RTMP-ingest-from-StreamPack-issue-7cc173d8f1ac440e80cc88146721604a

**Comment by clacladev** [comment]
Issue fixed by maintainer with https://github.com/ThibaultBee/StreamPack/issues/58

**Comment by victorges** [comment]
That's amazing!
