### ISSUE TITLE
Upload modal should error when user has hit rate limit

### ISSUE THREAD

**Issue by pglowacky** [livepeer/studio#1540]
We've introduced new rate-limiting behavior where a user can upload up to 100 files, 5 concurrently uploading at a time. After they hit the 100 upload maximum, they will no longer be able to upload assets until some of the assets have been completed. 

If this occurs, an error similar to this is generated `user 8f175616-1a6d-4481-86f5-7351c041b5ca has reached the maximum number of concurrent tasks` Currently, the dashboard does not have any behavior to reflect this error, and the upload modal simply closes with no error messages. Assets are not uploaded, they just disappear. 

To solve this, we should surface some error language on the upload modal, after a user has attempted to upload. The message should read, "Looks like you've hit the maximum amount of uploads. Please try again in a few minutes." 

![image.png](https://images.zenhubusercontent.com/602ea479bcf4ef10a9aace61/6eec78cb-f34b-4a04-8b30-9c8d7ebcba7f)

**Comment by pglowacky** [comment]
As of this morning, the rate-limiting behavior is currently not working, so I cannot confirm this behavior. Once I do, I'll update this ticket to make sure it's accurate.

**Comment by pglowacky** [comment]
@clacladev this ticket is updated and ready to be actioned.

**Comment by clacladev** [comment]
@pglowacky is this error coming back from our backend? Or do you mean "if the user selects more than 100 elements in total?"
