### ISSUE TITLE
Race condition on VOD logic updating DB

### ISSUE THREAD

**Issue by gioelecerati** [livepeer/studio#1660]
**What's the problem? (required)** 

back when we implemented VOD last year we didn't do any kind of "transaction" logic in the database because we didn't have any abstraction for that. so all queries/updates etc are done sequentially 

if more than one is executing at the same time, not necessarily the right one is gonna leave the update. in this case, there was a "thread" doing the task completion flow together with another "thread" in an API call doing the "progress update" flow. the task got the right final update, but the asset got the "progress" update.

there is no quick fix for this apart from properly implementing mutex/transaction logic in the DB, which takes quite some refactoring work to do. Could be worth it if we start seeing this more often

**Comment by victorges** [comment]
Replaced with API-21 on Linear.
