### ISSUE TITLE
Deleting Multiple Streams Broken

### ISSUE THREAD

**Issue by ericxtang** [livepeer/studio#171]
**Describe the bug (required)**
The functionality of deleting multiple streams is broken.

**Expected behavior (required)**
Able to select multiple streams and delete them at the same time.

**To Reproduce (required)**

1. Go to "streams"
2. Select multiple streams
3. Try to delete them

**Device (required):**

Chrome

**Screenshots (optional)**
<img width="1590" alt="Screen Shot 2020-12-15 at 3 53 10 PM" src="https://user-images.githubusercontent.com/345743/102271918-f85dcc00-3eed-11eb-9784-7150358ae239.png">

**Comment by iameli** [comment]
Ah yeah, I remember seeing this but it was in the middle of something else so I forgot to file. The worker doesn't forward on the body of the request for DELETEs.
