### ISSUE TITLE
Return multiple broadcasters when PlayDJ is requesting for the broadcaster list

### ISSUE THREAD

**Issue by ericxtang** [livepeer/studio#183]
Currently we only return a single broadaster because of the v1 architecture.  We want to offer PlayDJ an option to fall back to multiple broadcasters.

Implementation:
New `LP_BROADCASTER_INTERNAL` variable on the API server that provides the local broadcaster for internal Mist RTMP use. Other clients would use a different environment variable that provides the nearest two broadcasters instead.

**Comment by iameli** [comment]
Fixed by https://github.com/livepeer/livepeer-worker/commit/1f58caa39f1d30eecb928da488b150714e1d87d1
