### ISSUE TITLE
Inconsistent button styling on Livepeer.com Admin Users page

### ISSUE THREAD

**Issue by wohlner** [livepeer/studio#214]
https://livepeer.com/app/admin

The unavailable buttons are styled correctly in muted grey. However, the available buttons are not. Right now they are just bold text and instead should be styled like available buttons. For example of the correct styling, look at https://livepeer.com/app/admin/keys. The `create` button is available and styled correctly. Please fix the incorrectly styled buttons on https://livepeer.com/app/admin.
![Screen Shot 2021-01-19 at 8.34.35 AM.png](https://images.zenhubusercontent.com/5d51866c4b419616253bda2e/b429ae2b-08a4-48ff-8480-a0d9caebeb11)

On page one, it `previous page` (unavailable) and `next page` (available) buttons look like this.
![Screen Shot 2021-01-19 at 8.29.39 AM.png](https://images.zenhubusercontent.com/5d51866c4b419616253bda2e/1825b9b1-7436-47de-abef-833cbeeba5e9)

On page two, when both the `previous page` and `next page` buttons are available, they look like this.
![Screen Shot 2021-01-19 at 8.29.45 AM.png](https://images.zenhubusercontent.com/5d51866c4b419616253bda2e/e3e42fa1-d19f-4fda-b905-0da0f3e702f8)

Similar incorrect styling happens when I select the checkbox next to user
![Screen Shot 2021-01-19 at 8.33.20 AM.png](https://images.zenhubusercontent.com/5d51866c4b419616253bda2e/9d8b477e-b508-4465-ad61-f03a74629909)

**Comment by julianbenegas** [comment]
@wohlner I think this is already solved, although the disabled buttons do have an outline. Is that alright? Also, the pagination buttons are the arrows on the top left of the table.

![image](https://user-images.githubusercontent.com/40034115/106184067-d52a6b80-617f-11eb-937d-5abf9d4ebc11.png)

**Comment by wohlner** [comment]
Yep, your updates and the new buttons look good. Good work.

**Comment by julianbenegas** [comment]
Yup, looks good. Was clarifying cause i didn't made any changes actually. I think it was done by @darkdarkdragon 

Let me know if this can be closed, or you want something else addressed.

**Comment by wohlner** [comment]
No, you can close it.
