### ISSUE TITLE
Add `createdAt` and other timestamp fields to user object

### ISSUE THREAD

**Issue by iameli** [livepeer/studio#243]
Same as all the other `createdAt` fields — timestamp of when the user was created.

Could also use `verifiedAt` when their email becomes valid and `planChangedAt` when their plan changes.

`planChangedAt` gets overwritten each time the user upgrades or downgrades.

**Comment by wohlner** [comment]
Revise `updatedAt` to `planChangedAt`

**Comment by wohlner** [comment]
At minimum, `verifiedAt` and `planChangedAt` should be hidden from Livepeer.com API users
