### ISSUE TITLE
Unexpected key values for LP active sessions that are part of the same recording

### ISSUE THREAD

**Issue by wohlner** [livepeer/studio#286]
For the parent `stream` object with id `4eb3cc79-107e-4742-bfea-e74b4ecec186` and `record` set to `true`, I started my first livestream. 

I then ran this command to get a list of all recorded sessions for `stream` `id:  "4eb3cc79-107e-4742-bfea-e74b4ecec186"`
``` bash
curl -H 'authorization: Bearer <non-admin-api-key>' \
"https://livepeer.com/api/stream/4eb3cc79-107e-4742-bfea-e74b4ecec186/sessions?record=1"
```
This is the response I got, and it looks good. Just one session. The `record`, `recordingStatus` and counts for stuff like `sourceSegmentsDuration` all looks right.:
``` bash
[{
"id":"4eb3f10c-0d95-4967-8983-caba3f50717d",
"kind":"stream",
"name":"videorec+4eb3eiw3udnqovh2",
"record":true,
"region":"mdw",
"userId":"c5b4089e-0b35-4c2d-93b9-00d3fdb8228f",
"lastSeen":1614005521567,
"parentId":"4eb3cc79-107e-4742-bfea-e74b4ecec186",
"profiles":[{"fps":0,"gop":"2.0","name":"240p0","width":426,"height":240,"bitrate":250000},{"fps":0,"gop":"2.0","name":"360p0","width":640,"height":360,"bitrate":800000},{"fps":0,"gop":"2.0","name":"480p0","width":854,"height":480,"bitrate":1600000},{"fps":0,"gop":"2.0","name":"720p0","width":1280,"height":720,"bitrate":3000000}],
"createdAt":1614004592093,
"ingestRate":347344.32783608197,
"renditions":{},
"sourceBytes":41033353196,
"outgoingRate":647994.0029985008,
"sourceSegments":462,
"transcodedBytes":654601524,
"transcodedSegments":1848,
"sourceSegmentsDuration":905.967,
"transcodedSegmentsDuration":3623.8680000000013,
"recordingStatus":"waiting"}]`
```
Next I stopped my stream in OBS for about 30 seconds. And then I started recording again. As expected, it seems that behind the scenes, this new session was combined with the last one. After running the same command above, the response was still only one session. Great!
``` bash
[{
"id":"4eb31b62-9d6f-47b5-bf78-01674b37524f",
"kind":"stream",
"name":"videorec+4eb3eiw3udnqovh2",
"record":true,
"region":"mdw",
"userId":"c5b4089e-0b35-4c2d-93b9-00d3fdb8228f",
"lastSeen":1614005537573,
"parentId":"4eb3cc79-107e-4742-bfea-e74b4ecec186",
"profiles":[{"fps":0,"gop":"2.0","name":"240p0","width":426,"height":240,"bitrate":250000},{"fps":0,"gop":"2.0","name":"360p0","width":640,"height":360,"bitrate":800000},{"fps":0,"gop":"2.0","name":"480p0","width":854,"height":480,"bitrate":1600000},{"fps":0,"gop":"2.0","name":"720p0","width":1280,"height":720,"bitrate":3000000}],
"createdAt":1614005534499,
"ingestRate":347344.32783608197,
"renditions":{},
"sourceBytes":1261668,
"outgoingRate":647994.0029985008,
"sourceSegments":2,
"transcodedBytes":-692402496,
"transcodedSegments":8,
"sourceSegmentsDuration":3.9990000000000236,
"transcodedSegmentsDuration":15.995999999999185,
"recordingStatus":"waiting"}]
```
However, the `id` is new! And all the counters like for `sourceSegmentsDuration` reset. 

Furthermore, if I run `GET /stream/ 4eb3f10c-0d95-4967-8983-caba3f50717d` (the first session `id` before manually stopping and restarting my stream), this is returned. `recordingStatus` goes away and `previousSessions` appears.
``` bash
{"id":"4eb3f10c-0d95-4967-8983-caba3f50717d",
"kind":"stream",
"name":"videorec+4eb3eiw3udnqovh2",
"record":true,
"region":"mdw",
"userId":"c5b4089e-0b35-4c2d-93b9-00d3fdb8228f",
"lastSeen":1614005533571,
"parentId":"4eb3cc79-107e-4742-bfea-e74b4ecec186",
"profiles":[{"fps":0,"gop":"2.0","name":"240p0","width":426,"height":240,"bitrate":250000},{"fps":0,"gop":"2.0","name":"360p0","width":640,"height":360,"bitrate":800000},{"fps":0,"gop":"2.0","name":"480p0","width":854,"height":480,"bitrate":1600000},{"fps":0,"gop":"2.0","name":"720p0","width":1280,"height":720,"bitrate":3000000}],
"createdAt":1614004592093,
"ingestRate":347344.32783608197,
"renditions":{},
"sourceBytes":42369148092,
"outgoingRate":647994.0029985008,
"partialSession":true,
"sourceSegments":462,
"transcodedBytes":654601524,
"previousSessions":["4eb3e079-80f3-412e-9e0f-b98eb61dd074"],
"transcodedSegments":1848,
"recordObjectStoreId":"b4b1810a-4ced-4777-967e-c6058a9be1cf",
"sourceSegmentsDuration":905.967,
"transcodedSegmentsDuration":3623.8680000000013}
```

This is will be unexpected for the user. In this workflow, they have to wait until the end of the livestream session to know the proper `stream` session `id` to request a playback URL from. And they might be confused about the disappearing and appearing `stream` paramenters.

### To make this better for the user, we should add information about it in the documentation at minimum.

But it could also be beneficial if making the request to `GET /stream/ 4eb3f10c-0d95-4967-8983-caba3f50717d` (the first session `id` before manually stopping and restarting my stream) also returned the expected result while the stream was active.

**Comment by darkdarkdragon** [comment]
@wohlner can you elaborate on that?

**Comment by wohlner** [comment]
@darkdarkdragon you beat me to it! I was busy writing everything out. Let me know if you have any questions about what I put in the description. No work required on your end now, the feature is still ready for private beta in my opinion.

**Comment by wohlner** [comment]
On a related note: `GET /stream/4eb3cc79-107e-4742-bfea-e74b4ecec186/sessions` does not return the partial session, only the session with `id` `4eb31b62-9d6f-47b5-bf78-01674b37524f`. This is wonderful.

**Comment by wohlner** [comment]
This is very closely related to https://app.zenhub.com/workspaces/video-user-team-5dd2c75e4ee08500015994d7/issues/livepeer/livepeer-com/287. That documents when the stream is complete. This bug documents when the livestreaming session is still active.

**Comment by wohlner** [comment]
@darkdarkdragon I think this can be closed because you addressed it in https://app.zenhub.com/workspaces/video-user-team-5dd2c75e4ee08500015994d7/issues/livepeer/livepeer-com/287.
