### ISSUE TITLE
Prevent recording manifest request timeout for very long streams

### ISSUE THREAD

**Issue by wohlner** [livepeer/studio#288]
At the private beta launch for this feature, @darkdarkdragon reported a risk for very long streams (guessing 8+ hour streams). We have only tested streams 4 hours long. But Ivan anticipates that manifest requests for these very long streams will timeout. Even though recording data won't be lost, this is a bad user experience.

**Comment by darkdarkdragon** [comment]
@wohlner I've tested 13 hours stream - manifest generation takes 7 seconds. So I think we're good for now.
