### ISSUE TITLE
Stream page with a lot of sessions is unresponsive --> add pagination

### ISSUE THREAD

**Issue by darkdarkdragon** [livepeer/studio#306]
**Describe the bug (required)** A clear and concise description of what the bug
is.
Right now sessions table shows all the sessions - and if it is a lot that makes page unresponsive
Example https://livepeer.com/app/stream/2f10dd32-1296-4091-8d8e-5a6c11abdcb3

**Expected behavior (required)** A clear and concise description of what you
expected to happen.
Page should work smoothly

**To Reproduce (required)** Steps to reproduce the behavior:
1. Go to https://livepeer.com/app/stream/2f10dd32-1296-4091-8d8e-5a6c11abdcb3

**Comment by darkdarkdragon** [comment]
@wohlner do we need to show session if it was not recorded?

**Comment by wohlner** [comment]
Yes, we will want to still show non-recorded sessions. I'll work on the UI. I think this points to a larger pagination problem. Let's talk about it in planning in a few minutes.

**Comment by wohlner** [comment]
Get designs to Ivan asap. to do: @wohlner
