### ISSUE TITLE
Recording UI checkbox should be on/off radio buttons

### ISSUE THREAD

**Issue by wohlner** [livepeer/studio#324]

**Comment by darkdarkdragon** [comment]
@wohlner I can't find any radio button in our design. I can take standard one:
![image](https://user-images.githubusercontent.com/2035357/112082281-c2d01b00-8b8d-11eb-8ab9-224333b56175.png)

So how should it look?

**Comment by wohlner** [comment]
That looks great. Please change the following copy:

- "Record stream" to "Record sessions"

**Comment by wohlner** [comment]
Also, please take a look at https://docs.google.com/drawings/d/1S7kabGgV-qvCtVFYs2zSnIyODfXsQ9vhnfTdYy-uFKY/edit to see where the record radio buttons row should be (below ingest/playback URLs and above renditions)
