### ISSUE TITLE
Inaccurate Error Message On Test Player

### ISSUE THREAD

**Issue by ericxtang** [livepeer/studio#353]
**Describe the bug (required)** A clear and concise description of what the bug is.
When you paste the URL of an inactive Livepeer stream into the test URL, it says `The stream exists but the url is invalid.`.  Instead, it should say `The stream exists but it's inactive.` (This was a point of friction during an impromptu user testing session).

![Screen Shot 2021-04-08 at 2 32 01 PM](https://user-images.githubusercontent.com/345743/114078859-77995600-9877-11eb-98a1-2dfdd0746772.png)

**To Reproduce (required)** Steps to reproduce the behavior:

1. Paste any valid, inactive Livepeer playback URL into the test player

**Comment by pglowacky** [comment]
test player in this format no longer exists!
