### ISSUE TITLE
Livepeer.com Webhooks MVP

### ISSUE THREAD

**Issue by wohlner** [livepeer/studio#356]
### The MVP includes webhooks for the following:

1. `stream.session.active`
The "parent" `stream` object's `isActive` value is now `true` and the .m3u8 HLS URL constructed from the `playbackId` now works. 

2. `stream.session.idle`
The "parent" `stream` object's `isActive` value is now `false` and the .m3u8 HLS URL constructed from the `playbackId` no longer works.

3. `stream.session.recording.started`
For a the new `session` object, `record:true`, `isActive:true` and `recordingStatus:waiting`.

4. `stream.session.recording.ready`
For a the new `session` object, `record:true`, `isActive:false` and `recordingStatus:ready`.

### Rules around retries
- Livepeer.com expects a `2xx` response to webhook events. The request will time out after 5 seconds. 
- Retry to `POST` the event with an exponential backoff up to 60 minutes 

###  Additional features to make webhooks MVP work:
- Configure URL(s) to notify in the Livepeer.com dashboard
- Configure individual webhooks per notification URL
- verifiable webhook signatures

### Out of Scope for webhooks MVP:
- specifying production vs test environments for webhooks. At MVP, the users will need to create another Livepeer.com account to test in stage, for example.
- disabling, but not deleting, a webhook
- `stream.session.sceneDetected` webhook
- error webhooks (cc @iameli)

**To discuss**
- `stream.connected` and `stream.disconnected`
- Remove webhook URL `name` parameter

**Comment by darkdarkdragon** [comment]
@wohlner 
> 2. `stream.session.idle`
> The "parent" `stream` object's `isActive` value is now `true` and the .m3u8 HLS URL constructed from the `playbackId` no longer works.

Should it be "is now `false`"?

**Comment by darkdarkdragon** [comment]
@wohlner 
> Retry to POST the event with an exponential backoff up to 60 minutes

What to do with blocking webhooks? Or we're removing blocking webhooks?

**Comment by wohlner** [comment]
Yes, remove blocking webhooks. @ya7ya @darkdarkdragon 

While the idea is interesting, I am not convinced that preventing the stream from starting until we receive a 2XX is appropriate. It takes away some control from the livepeer.com user and it could create a confusing experience for the live streamer.

**Comment by darkdarkdragon** [comment]
@wohlner 
> While the idea is interesting, I am not convinced that preventing the stream from starting until we receive a 2XX is appropriate.

It was meant as way for UGP platforms builders to authenticate their users - so they could have one stream in Livepeer API and use wildcards streams (which we don't have yet) to match their users in their own database (also I thought this was the primary reason we want wildcard streams). 
Just want to be clear that we're not building this.

**Comment by wohlner** [comment]
@darkdarkdragon that's helpful context. Webhooks will exist without wildcard streams for a bit. Let's remove blocking webhooks now.

**Comment by darkdarkdragon** [comment]
@wohlner 
Can one webhook receive multiple events types? Or we have one webhook per event type and so we should create separate webhook object per event type, even if url is the same?

**Comment by wohlner** [comment]
> @wohlner 
> Can one webhook receive multiple events types? Or we have one webhook per event type and so we should create separate webhook object per event type, even if url is the same?

Take a look at the wireframes for the dashboard updates. You can add multiple event types to a single webhook url destination. But let's keep one event per webhook object.
