### ISSUE TITLE
Livepeer.com Dashboard: Configure URL(s) to notify and specify webhook events

### ISSUE THREAD

**Issue by wohlner** [livepeer/studio#357]
New Webhooks tab to the right of the API Keys tab. (In the future, we will combine the API keys and Webhooks tabs into a new Developers section)

### Webhooks list page
Clicking on a webhook URL takes the user to the webhook details page below
![Webhooks MVP in Livepeer.com Dashboard.jpg](https://images.zenhubusercontent.com/5d51866c4b419616253bda2e/b3bc4427-219a-4a4a-a09f-1171a06bc00c)

### Create a new webhook page
Clicking save takes the user to the webhook details page below
![CREATE, Webhooks MVP in Livepeer.com Dashboard (1).jpg](https://images.zenhubusercontent.com/5d51866c4b419616253bda2e/4a7c7e79-44a1-4a24-ab76-d38dbc7ffcc9)

###  Webhook details page below
Clicking edit takes the user back to the webhooks configuration page below
![CONFIGURE landing, Webhooks MVP in Livepeer.com Dashboard.jpg](https://images.zenhubusercontent.com/5d51866c4b419616253bda2e/471a8dd6-8435-42de-9384-4bff9e09a9f7)

### Webhook configuration page
Clicking cancel or save takes the user back to the webhook list page above.
Clicking delete prompts a pop-up with the heading "Are you sure? and the copy "Are you sure you want to delete this webhook? Deleting a webhook cannot be undone." Once the user confirms, they are taken to the webhooks list page above.
The drop down lists all available livepeer.com webhooks.
Clicking the "x" to the right of the webhook, removes it.
![CONFIGURATION EDIT, Webhooks MVP in Livepeer.com Dashboard.jpg](https://images.zenhubusercontent.com/5d51866c4b419616253bda2e/a1ce17c6-0d75-4e6f-b14e-06f4ecd3d575)

**Comment by pglowacky** [comment]
Will be included in the Dashboard redesign but DOES NOT need to be completed before then. 

cc @adamsoffer

**Comment by adamsoffer** [comment]
@pglowacky sorry a bit confused...this doesn't need to be completed before when?

**Comment by adamsoffer** [comment]
After reviewing this feature more thoroughly I estimate ~3-4 days worth of work (design + frontend).

**Comment by pglowacky** [comment]
@adamsoffer Apologies, I see why my comment was confusing. The note was to indicate to the video user team that they didn't have to work on it before we launched the dashboard redesign. We'll work on this ticket as part of the dashboard work and therefore is not a blocker to launching webhooks into production.

**Comment by adamsoffer** [comment]
Ah right. Thanks for the clarification.
