### ISSUE TITLE
Livepeer Doc Pages Are Not SEO Friendly

### ISSUE THREAD

**Issue by ericxtang** [livepeer/studio#358]
**Describe the bug (required)** A clear and concise description of what the bug is.
Based on feedback from Mark:
> docs all have duplicate titles, metadata and low word count ... all of these factors have a high impact on SEO, the 1st two are simple fixes

**Expected behavior (required)** A clear and concise description of what you expected to happen.
Doc pages should have different titles and different metadata.

**Comment by adamsoffer** [comment]
Documentation guides all now have unique meta titles and descriptions.
