### ISSUE TITLE
Add new 'session' table

### ISSUE THREAD

**Issue by darkdarkdragon** [livepeer/studio#361]
## Problem

Currently we have `sessions` which is basically same stream object but with `parentId` set. This `sessions` objects created by Mist when it starts transcoding. 
But recently we introduced concept of `user session` - which internally consists of number of `regular` `sessions`. Currently `user session` object gets constructed on the fly from `regular session` objects. This is inefficient and complicates code.

## Solution

Create new `session` table which will track properties of `user` session.

**Comment by wohlner** [comment]
In the response, please be sure to include the following parameters

```
lastSeen
isActive
sourceSegments
transcodedSegments
sourceSegmentsDuration
transcodedSegmentsDuration
sourceBytes
transcodedBytes
id
kind
name
record
userId
parentId
playbackId (inherit from the "parent" stream object")
profiles
createdAt
ingestRate
outgoingRate
recordingStatus (do not show if record:false)
recordingUrl (do not show if record:false)
```
@darkdarkdragon

**Comment by darkdarkdragon** [comment]
@wohlner do we really need `isActive` field on session object? It's kinda hard to manage and what's the purpose? This information is available on stream object.

**Comment by wohlner** [comment]
I'm ok leaving it out. For streams without recording on, isActive on the parent stream should suffice. For streams with recording turned on, the isActive on the parent stream combined with the recordingStatus on the session should give the user all they need to know. @darkdarkdragon
