### ISSUE TITLE
stream.session.active webhook

### ISSUE THREAD

**Issue by wohlner** [livepeer/studio#363]
The "parent" stream object's `isActive` value is now `true` and the .m3u8 HLS URL constructed from the `playbackId` now works. 

Response:
```json
{
 "event": "stream.session.active",
  "kind": "webhook",
  "createdAt": 1615927138787,
  "webhookUrl": "https://example.com/example_endpoint",
  "session": {
	"id":{session-id},
	"parentId":{parentId}
         "name":{name-of-session},
	 "createdAt":1615927138787
	}
}
```

**Comment by darkdarkdragon** [comment]
@wohlner names of our sessions is always `video+playbackId` (set by Mist when created)
So not sure it is useful for users.
