### ISSUE TITLE
Postgresql Message Queue adapter

### ISSUE THREAD

**Issue by ya7ya** [livepeer/studio#378]
We'd like to use Postgresql as a Msg Queue for the webhooks
details: https://stackoverflow.com/questions/13005410/why-do-we-need-message-brokers-like-rabbitmq-over-a-database-like-postgresql/13005551#13005551

The adapter needs to mimic a Msg queue interface
- [ ] emit to channel 
- [ ] channel handler

**Comment by darkdarkdragon** [comment]
@ya7ya 
1. Any chance we could use CockroachDb for this? It has PostgreSQL wire-compatible protocol, so from our side it will be almost the same. But that way we'll have a chance to get hands-on experience with CochroachDb - with the intention to replace centralized PostgresSQL with it eventually.
2. Also it would be good for queue to have 'postponed' messages - like 'that message should be processed after 5 min after creation'. That would help with processing 'recording status' of the session.

**Comment by ya7ya** [comment]
@darkdarkdragon 
1. Yeah the next logical step is to use cockroachDB but when I discussed it with the team it seems this would be out of scope for this Epic and it'd mean there is some DevOps work needed to get it off the ground unlike Postgres which we already use in Prod. 

I do agree that CockroachDB would be an overall better match as a datastore for the livepeer-api 👍 

2. Yes this mechanism needs to be implemented either way to allow for a backOff strategy in case the client's server doesn't respond with a 2xx, one way of doing that is to have the wait time as a parameter when firing and it defaults to 0.
