### ISSUE TITLE
Add field for enabling scene classification on the Stream object

### ISSUE THREAD

**Issue by iameli** [livepeer/studio#451]
I created a branch in livepeer-com https://github.com/livepeer/livepeer-com/tree/yf/scene-classification-example that contains:

- An example of the config that the stream auth webhook should pass to a B in order to configure scene classification https://github.com/livepeer/livepeer-com/commit/7b289bf79f566cb6ecb44c1643fecad8a8a06982
- An example of a detection webhook that accepts results posted by a B (currently just logs the results) https://github.com/livepeer/livepeer-com/commit/5e6156061953f914a377d488a0710be634f80080

**Comment by iameli** [comment]
The shape of the incoming go-livepeer object is defined here https://github.com/livepeer/go-livepeer/issues/1917

**Comment by victorges** [comment]
Cool, thanks for the examples!
