### ISSUE TITLE
Table refactor

### ISSUE THREAD

**Issue by adamsoffer** [livepeer/studio#454]

**Comment by julianbenegas** [comment]
For friday Jun 18.

- <Table /> to handle table state (including header and actions).
- Use SWR; receive a `fetcher` from parent and hold the rows inside.

**Comment by adamsoffer** [comment]
Updated requirements:
- Add a "Status" filter to streams and sessions tables so users can filter by active or idle streams
- Add filter state as query parameters when the filter is applied (The home page will use this to link directly to an active streams view).
- Track total number of checked filters 
![image](https://user-images.githubusercontent.com/555740/122586062-31f0ca80-d02a-11eb-90d7-a4e8b9f3e96b.png)
