### ISSUE TITLE
Webhook Management View

### ISSUE THREAD

**Issue by adamsoffer** [livepeer/studio#458]
There are two tickets with low-fi wireframes that relate to this issue that relates to this issue:

1) [Creating and configuring webhooks](https://app.zenhub.com/workspaces/video-user-team-5dd2c75e4ee08500015994d7/issues/livepeer/livepeer-com/357)
2) [Displaying webhooks signatures](https://app.zenhub.com/workspaces/video-user-team-5dd2c75e4ee08500015994d7/issues/livepeer/livepeer-com/362)

**Comment by pglowacky** [comment]
I'll confirm, but creating and configuring webhooks is the priority. It's currently unknown how much progress we've made on the webhooks signature. At that point, we'll understand the true scope of this ticket.

**Comment by adamsoffer** [comment]
Just wrapped up the webhooks management view. Viewable on [the preview url](https://livepeer-com-git-as-dashboard-redesign-livepeerorg.vercel.app/).
