### ISSUE TITLE
Source-only Streams Output Multiple Transcoded Renditions

### ISSUE THREAD

**Issue by ericxtang** [livepeer/studio#538]
**Describe the bug (required)** 
The user can create a stream with `[]` as profiles, but when the stream starts, the output consists the default ABR ladder.  This doesn't meet the user's expectations.

Also, it'll be nice to offer a "source-only" - for example, users who ONLY want to multistream would want this.

**Expected behavior (required)** 
When profiles is `[]`, Only the source is in the output.  No transcoding happens.

**To Reproduce (required)** Steps to reproduce the behavior:

1. Create a stream with `[]` as profiles
2. Stream into it
3. You see 4 output renditions

**Comment by yondonfu** [comment]
Closing in favor of https://github.com/livepeer/studio/issues/1147 since that has additional details, but folks can refer to this issue as the original report.
