### ISSUE TITLE
Front End Designs for Multistream 

### ISSUE THREAD

**Issue by pglowacky** [livepeer/studio#561]
Using the low fidelity wireframes [in this doc](https://docs.google.com/document/d/16lKP3p6WKBRA1O0f6Dkb7UkjpjbbycpgFWuZZFJOviQ/edit#heading=h.svlztax2lvcw), create high fidelity designs of the multistream dashboard experience.

**Comment by adamsoffer** [comment]
https://www.figma.com/file/z09WhEiP7gopgNZ0QPuOB7/Dashboard?node-id=43%3A1796
