### ISSUE TITLE
24/7 Stream Investigation

### ISSUE THREAD

**Issue by pglowacky** [livepeer/studio#594]
During Eli's 24x7 stream, we found that the stream would go through a rename process at least once each day. To complete the investigation, we should: 

1) Determine root cause. Is this something happening at Mist?
2) Make a recommendation: Should we eliminate renames? If so, how could we eliminate renames? Changes at Mist or some other way?

**Comment by pglowacky** [comment]
Just got a report from user wileyjacobs@protonmail.com that his 24/7 stream is "going idle" which is causing buffering for viewers. The fix, they report, is to restart OBS. 

Since we're getting real-life people experiencing this issue, let's address this during next week's Tech Debt week.

**Comment by pglowacky** [comment]
Recommendations from Eric:

1) Turn off transcoding and see if that fixes the problem
2) Run another test but restart it every 12 hours and see if that fixes the problem

**Comment by victorges** [comment]
How often are their stream going idle? Could it just be when we eventually restart/kill the `mist` instance where they started streaming to?

**Comment by pglowacky** [comment]
@victorges Ah, sorry didn't see this comment! Wiley is now resetting the stream every 12 hours, and consistently seeing issues around 5am ET, which makes me think there could be a specific amount of time between when the stream restarted to when he experiences issues.
