### ISSUE TITLE
Bug: Customer only sees one rendition 

### ISSUE THREAD

**Issue by pglowacky** [livepeer/studio#645]
Our integration with the mist-api-connector and the API may be causing streams to be marked as 'inactive' erroneously when a stream is started and stopped in quick succession. This is causing customers to see only one rendition in their players, causing confusion. 

We should do some tests in order to recommend to customers some amount of time to wait before stopping and restarting streams. 

_**It is currently unclear if this is a display issue (i.e. transcoding is happening normally) or if no transcoding is happening. Step 1 is to investigate whether or not transcoding is happening.**_

**Comment by pglowacky** [comment]
Assigning Victor because we've been working through this together.

**Comment by pglowacky** [comment]
@victorges What do you think about calling this resolved now? Seems like Dave is in good shape.

**Comment by victorges** [comment]
Sounds good! I'm gonna ask him how did the streams go this weekend and we
can keep investigating/iterating on any weird issues he finds, but we don't
need to keep an issue open about it.

**Comment by victorges** [comment]
Seems to be that same b-frame issue after all. The problem happened when the user streamed a video that had been recorded by a previous Wowza deployment of them, which would not surprise me if they contained some B-frames after all.

They reported having no errors when streaming other videos, not recorded by Wowza, that they pre-processed themselves with ffmpeg (although from a product perspective, this required pre-processing seems to beat the purpose of using Livepeer at all).
