### ISSUE TITLE
Remove email verification step during customer onboarding

### ISSUE THREAD

**Issue by pglowacky** [livepeer/studio#666]
[Per this proposal, ](https://docs.google.com/document/d/1AKHfHJIKKs4sKcNqw8s3YYPfCO-qqf0DFhvo1Io8CS8/edit#) I'd like to remove the step where customers are required to verify their email before being dropped into the dashboard. 

Requirements:
- Customers should use the registration page to sign up for an account
- Customer information is automatically saved into Hubspot (as they are today) 
- Verification email is still sent, although it is not required to access the account
- Copy on the verification email needs to be changed (details below) 
- Once customer signs up for an account, they are immediately directed to the dashboard (elimination of the screen that requires verification) 
- IMPORTANT: we will need to be able to easily and quickly roll back these changes. 

## Customer Experience: 

1. User registers at Livepeer.com/register (no change) 

![image.png](https://images.zenhubusercontent.com/602ea479bcf4ef10a9aace61/650564a5-8d78-4a7e-a9c6-eabac7190548)

2. Customer account is created and immediately dropped into an account. 
Change: removal of the verification step

![image.png](https://images.zenhubusercontent.com/602ea479bcf4ef10a9aace61/597762b5-cd0e-4e62-a235-38070e98e5d8)

3. Customer is sent a verification email to email on file, although there is no incentive to verify 

![image.png](https://images.zenhubusercontent.com/602ea479bcf4ef10a9aace61/2e043987-5510-4423-9433-afc098e0bba6)

Copy is changed to: Please verify your email address to ensure that you can change your password or receive updates from us.

**Comment by MRTIBBETS** [comment]
When ready, I'd like to review the pull request for any Verification Email polish, please. Thanks in advance!

**Comment by adamsoffer** [comment]
@pglowacky I think if we remove email verification we should implement some spam prevention? [Recaptca](https://developers.google.com/recaptcha/docs/v3)? I think we get a lot of spam sign ups as is.

**Comment by FullStackTiger** [comment]
@pglowacky Also I think:
- form validations
- email checking backend API(real email address or not)

**Comment by adamsoffer** [comment]
@FullStackTiger I've discussed with Paige and opened this issue. https://github.com/livepeer/livepeer-com/issues/699

**Comment by FullStackTiger** [comment]
After getting the score from Recaptcha API
if score < 0.5(maybe the user is spam), we should use an email verification workflow?
if score >= 0.5, remove email verification step?
@pglowacky @adamsoffer

**Comment by pglowacky** [comment]
@adamsoffer @FullStackTiger Hang on. I thought that the invisible reCaptcha wouldn't interrupt users? Sending some users to verification will alter the results of this two-week experiment.

**Comment by adamsoffer** [comment]
@pglowacky this happens in the background. It won't interrupt any user flow. It will simply prevent bots from submitting the form.

**Comment by adamsoffer** [comment]
Vukasin - if the user is a bot we don't have to take any action, we can just not submit the registration form.

**Comment by pglowacky** [comment]
@adamsoffer Is there any chance a good user could get marked as a bot? If there's not, I'm okay with proceeding. Just hoping to get clean results 🙏

**Comment by adamsoffer** [comment]
@pglowacky I'll say it's highly improbable. Nearly every saas product registration form uses it these days without issue. But let's perform a bunch of test registrations on staging so we can have 100% confidence in it!

**Comment by pglowacky** [comment]
@adamsoffer Sounds excellent! Thanks 👍
