### ISSUE TITLE
Change Copy on Dashboard Homepage

### ISSUE THREAD

**Issue by pglowacky** [livepeer/studio#676]
I'd like to change the copy in the tutorial on the homepage in the Livepeer.com dashboard. 

Current State:

![image.png](https://images.zenhubusercontent.com/602ea479bcf4ef10a9aace61/e1cb909b-31a6-4da8-aa9c-a44fe4d40604)

- Change title to: Welcome to your dashboard{firstName && `, ${firstName}`

- Create your first live stream

No code required! All you need to do is create a RTMP stream with broadcasting software like OBS Studio or streamlabs. Here’s how.

1. Tap + Create stream below give your stream a name
2. From the Stream Details, copy the Playback URL and Stream Key.
3. Then paste them into your broadcasting software.
4. Tap “Go Live” in the broadcasting software to start streaming.

Need more help? Read our step-by-step guide.

[Get started tutorial](https://livepeer.com/docs/guides/start-live-streaming/tutorial) (BUTTON) 

- Build with the Livepeer API 

Ready to code? The Livepeer API is nimble and designed for customization.  All you need to do is create an RTMP stream with broadcasting software like OBS Studio, streamlabs, or ffmpeg. 

[Explore the API](https://livepeer.com/docs/api-reference) (BUTTON) 

- Create your own app 

Livepeer video infrastructure is designed to serve your app, from the ground up and at scale. Get started by reviewing and cloning one of our sample apps.

[Clone and create](https://livepeer.com/docs/guides/application-development/example-app) (BUTTON)

**Comment by pglowacky** [comment]
cc @MRTIBBETS

**Comment by MRTIBBETS** [comment]
For reference, here's the GDoc we worked out the copy: https://docs.google.com/document/d/1FExa3iOBTsMmsbgjbjjFz274KceCajMkf3QKlCBusWw/edit?usp=sharing

It might be helpful for some context when updating the code.

**Comment by FullStackTiger** [comment]
https://github.com/livepeer/livepeer-com/pull/697
