### ISSUE TITLE
Set up CNAME for livepeer.com/jobs and livepeer.org/jobs

### ISSUE THREAD

**Issue by pglowacky** [livepeer/studio#683]
With our DNS provider, set up a CNAME for livepeer.com/jobs and livepeer.org/jobs pointing to ext.teamtailor.com  

More instructions here: https://support.teamtailor.com/en/articles/113671-use-your-own-domain

**Comment by iameli** [comment]
Registering livepeer.jobs could be an option too 😃

**Comment by pglowacky** [comment]
Freakin' love that, editing ticket NOW

**Comment by pglowacky** [comment]
@FullStackTiger Heads up that this is deprioritized until I discuss with Shay on Friday and then we'll reprioritize at that time.

**Comment by pglowacky** [comment]
@MRTIBBETS @adamsoffer @FullStackTiger I've updated this ticket to NOT include another domain, just to set up a CNAME that points to Team Tailor. 

@MRTIBBETS @adamsoffer Are you +1 to proceed with the scope of this ticket changed?

**Comment by MRTIBBETS** [comment]
Shared over DM:

This means that Team Tailor would host the page and contents and stuffs, we'd just point people there from .org/jobs and .com/jobs, ya? Sounds like a decent solution to me, with minimal side effects if any. I say go for it!

If I can help with any styling, holler at me.

**Comment by pglowacky** [comment]
@iameli Shay mentioned that you were taking this on. Is that true?

**Comment by iameli** [comment]
I added records for Livepeer.com but I don't have access to Livepeer.org — only @ericxtang and @dob do.

**Comment by pglowacky** [comment]
I pinged @ericxtang asking for help or to give you permissions. Thanks for jumping in, @iameli!
