### ISSUE TITLE
Add recaptcha v3 to sign up form

### ISSUE THREAD

**Issue by adamsoffer** [livepeer/studio#699]
https://developers.google.com/recaptcha/docs/v3

**Comment by FullStackTiger** [comment]
Could you provide the [recaptcha key](https://www.google.com/recaptcha/admin/create)?
or Should I create it on my side?
@adamsoffer

**Comment by FullStackTiger** [comment]
We need to discuss more details for spam prevention.

![image.png](https://images.zenhubusercontent.com/616efed4bc03b82db7d9e3ae/7a45789c-db30-4da2-aa10-24959b608fba)
I am curious how to get a score the reCAPTCHA v3 returns,  As you can see on the screenshot, should I send the token that gets from "grecaptcha.execute" to the backend to get the score? or should I get the score on the nextjs frontend side?

1. Call the Recaptcha API(https://www.google.com/recaptcha/api/siteverify) on the frontend side: 
- score < 0.5 : the user is spam?

2. Send the grecaptcha.execute token to the backend:
-  I can add the token to the register endpoint like this:
```
    email,
    password,
    firstName,
    lastName,
    organization,
    phone,
    grecaptchaToken
```

- or can send the token to another specific API

@adamsoffer  @iameli  @pglowacky

**Comment by adamsoffer** [comment]
We'll need to add a `/verify` endpoint. https://prateeksurana.me/blog/integrating-recaptcha-with-next/#verifying-captcha-via-nextjs-api-routes

Instead of using next routes as described in the above guide we'll want to add this endpoint inside our `api` package. Can you open a separate PR with this endpoint?

**Comment by adamsoffer** [comment]
On second thought, this logic can also go inside the registration handler https://github.com/livepeer/livepeer-com/blob/master/packages/api/src/controllers/user.js#L91

**Comment by FullStackTiger** [comment]
https://github.com/livepeer/livepeer-com/pull/732
