### ISSUE TITLE
Search in docs isn't picking up new pages / changes

### ISSUE THREAD

**Issue by pglowacky** [livepeer/studio#700]
We currently use Agolia as our search function on livepeer.com/docs. Occasionally, we need to have it crawl through the pages to ensure that the search stays updated.

**Comment by pglowacky** [comment]
@adamsoffer can you provide detail on how to do this to @FullStackTiger?

**Comment by MRTIBBETS** [comment]
For what it's worth, I shared an example of this issue on another Issue: https://github.com/livepeer/internal-project-tracking/issues/238#issuecomment-964825761

Sharing here simply as a reference.

**Comment by FullStackTiger** [comment]
https://github.com/livepeer/livepeer-com/pull/750

**Comment by FullStackTiger** [comment]
please check it @pglowacky @MRTIBBETS
