### ISSUE TITLE
Video Segment Too Long

### ISSUE THREAD

**Issue by ericxtang** [livepeer/studio#72]
**Describe the bug (required)**
The output video segment length from livepeer.com is not close to 2 seconds

**Expected behavior (required)**
The Livepeer transcoders tries to create uniform segment lengths of 2s chunks

**To Reproduce (required)**

1. Create a stream in livepeer.com
2. Stream into the ingest using ffmpeg and the playdj.mp4 input file: `ffmpeg -re -i https://eric-test-livepeer.s3.amazonaws.com/playdj.mp4 -c copy -f flv rtmp://mdw-rtmp.livepeer.com/live/{stream-key}`
3. Curl the output video playlist
4. The output segments range from 8 to 10 seconds

<img width="1587" alt="Screen Shot 2020-09-06 at 7 03 37 PM" src="https://user-images.githubusercontent.com/345743/92337189-dc889580-f075-11ea-9699-82186cf850c6.png">
<img width="1603" alt="Screen Shot 2020-09-06 at 7 18 04 PM" src="https://user-images.githubusercontent.com/345743/92337190-dd212c00-f075-11ea-9cfd-dce97f82498a.png">

**Comment by pglowacky** [comment]
@ericxtang Is this bug still worth solving?

**Comment by ericxtang** [comment]
@pglowacky let's close this ticket.
