### ISSUE TITLE
Dashboard sorting & searching doesn't work with many streams

### ISSUE THREAD

**Issue by iameli** [livepeer/studio#722]
1. None of the sorting options on the dashboard seem to work. This is sorted by "Created", descending. The bottom of the page shows a stream from 2020, but not a stream I created yesterday.

![image](https://user-images.githubusercontent.com/257909/141509274-b7fe8581-33c3-40de-8336-1b2d47c87c11.png)

Hitting "next" shows me different streams, seemingly unrelated to creation time.

![image](https://user-images.githubusercontent.com/257909/141509414-c8855eb0-022f-438c-b93b-f41530c0c93c.png)

2. Searching for the word "test" using this mechanism...

![image](https://user-images.githubusercontent.com/257909/141509579-308d23a7-ca46-47a4-8ae6-7341edf6d3b2.png)

Doesn't work if you're several pages deep when you make the search. You get this screen instead:

![image](https://user-images.githubusercontent.com/257909/141509908-ad578c76-7d7f-4b8c-8c91-410d3cdac327.png)

**Comment by FullStackTiger** [comment]
https://github.com/livepeer/livepeer-com/pull/736

**Comment by iameli** [comment]
Re-opening — could you take a look at what's going on with the `lastSeen` column? Sorting by it yields this
![image](https://user-images.githubusercontent.com/257909/142803635-bd8fbf3d-4835-425a-887c-90c9f4c064cf.png)
But I have this stream, last seen today:
![image](https://user-images.githubusercontent.com/257909/142803681-c57ff945-e212-43a1-9441-b4a3ef5c6012.png)

**Comment by FullStackTiger** [comment]
https://github.com/livepeer/livepeer-com/pull/741
