### ISSUE TITLE
Creating a new multistream target doesn't get reflected in the dashboard

### ISSUE THREAD

**Issue by iameli** [livepeer/studio#725]
Creating a new multistream target doesn't get reflected in the dashboard, just looks like this:

![image](https://user-images.githubusercontent.com/257909/141510916-4464eab8-3c38-45b3-b08a-bd0d254a8b2b.png)

**Comment by victorges** [comment]
A couple questions:
 - Was the problem that the dashboard didn't update automatically when you created the target, or that even after refreshing the page it still did not show up?
 - If the latter, how exactly did you create a multistream target? Did you PATCH a stream with a new target or did you just POST a new /multistream/target and then PATCH the stream (if you did PATCH it eventually)?

**Comment by iameli** [comment]
> Was the problem that the dashboard didn't update automatically when you created the target, or that even after refreshing the page it still did not show up?

Good question. If it was the latter, it was probably replication lag. Don't remember, sorry — filed this one quickly while I was screen sharing.

**Comment by FullStackTiger** [comment]
I can't see this issue on my side, can you see this issue on your side yet? @iameli

**Comment by FullStackTiger** [comment]
I think this issue was fixed since I already added the function that can't add multistream targets while a stream is active
@iameli
