### ISSUE TITLE
Link to Dashboard at top of Livepeer.com/docs

### ISSUE THREAD

**Issue by pglowacky** [livepeer/studio#731]
As a user on the dashboard, if I click on a link to the docs, there's no easy way for me to navigate back to the dashboard. 

To address this, please add a link to https://livepeer.com/dashboard at the top navigation of Livepeer.com/docs, like this:

![image.png](https://images.zenhubusercontent.com/602ea479bcf4ef10a9aace61/3361ea70-c625-4ae8-a85c-8932625cac2a)

**Comment by FullStackTiger** [comment]
https://github.com/livepeer/livepeer-com/pull/751
