### ISSUE TITLE
Gradient z-index issue

### ISSUE THREAD

**Issue by adamsoffer** [livepeer/studio#75]
The purple gradient is overlaid on top of the inner pages causing links to become unclickable. 

<img width="1281" alt="Screen Shot 2020-09-08 at 11 12 23 AM" src="https://user-images.githubusercontent.com/555740/92494962-5333a900-f1c4-11ea-8d1b-5aab9575ed6a.png">

**Comment by julianbenegas** [comment]
On it!

**Comment by julianbenegas** [comment]
Done
