### ISSUE TITLE
Add SRT Ingest URL to Dashboard

### ISSUE THREAD

**Issue by pglowacky** [livepeer/studio#752]
We now have SRT ingest! We should include the SRT ingest URL on the dashboard. 

SRT URLs look like this:

`srt://rtmp.livepeer.com:2935?streamid={stream-key}`

The stream key field should be auto-populated with the stream key. The stream key should be hidden on the dashboard view, as we do with the playback URL. However, when the copy button is clicked the full URL is used. 

Like this:

![image.png](https://images.zenhubusercontent.com/602ea479bcf4ef10a9aace61/5ed96cdc-ed0d-40c9-8b4a-751a3330a196)

Tooltip should read:

> SRT ingest is currently in beta. Ensure that your encoder and player is compatible with SRT.

**Comment by FullStackTiger** [comment]
![image.png](https://images.zenhubusercontent.com/616efed4bc03b82db7d9e3ae/70c6a437-6499-4a19-9003-655ccad0b388)
How to get this port number? @victorges @pglowacky

**Comment by pglowacky** [comment]
@FullStackTiger Port number should stay the same for all ingest URLs, no matter what the stream key is.
