### ISSUE TITLE
Stream health shows as "unhealthy" while stream is loading

### ISSUE THREAD

**Issue by pglowacky** [livepeer/studio#770]
## Current state

When beginning a stream, the stream health dashboard's global health indicator will display as "Unhealthy" while the stream is loading into the player. Once the video loads, the global stream indicator displays as "Healthy." 

[Video](https://drive.google.com/file/d/1a9zCxB9XFRz1xowHX8-YRlnCw-DnZdrj/view?usp=drivesdk)

This is a potential source of confusion for customers who may believe that there is something wrong with their streams when their stream simply hasn't loaded completely. 

## Desired state

How we display Multistream health solves this confusion by displaying a "Pending" health indicator until the multistream destination has connected. 

A "Pending" indicator for the global stream health indicator would solve this confusion

**Comment by victorges** [comment]
Hey @pglowacky, I was actually already brewing a fix for this one! Could you check if the dashboard version with https://github.com/livepeer/livepeer-com/pull/709 already fixes the issue you described here?

Vercel preview: https://livepeer-com-git-vg-fixhealth-conditions-pour-over-livepeer.vercel.app/

**Comment by pglowacky** [comment]
@victorges I tested this twice and both times it showed the stream as "unhealthy" before flipping to "healthy." However, it did seem that the "unhealthy" state was for a much shorter period when I was previously testing, which may be sufficient for reducing confusion for now. 

I still think that the most ideal state is probably indicating that it's "pending" before flipping to "healthy"

**Comment by victorges** [comment]
Hmm weird, cause I did implement the pending feature. Gonna check if there's something wrong

**Comment by victorges** [comment]
Ah, I think it was a server issue after all. I think with this it works now: https://github.com/livepeer/livepeer-data/pull/29

**Comment by victorges** [comment]
@pglowacky when you have some time, could you check again if it looks good now before I merge the PR in livepeer-com? Can make any more UI changes in there. Same preview link as before: https://livepeer-com-git-vg-fixhealth-conditions-pour-over-livepeer.vercel.app/

**Comment by pglowacky** [comment]
LGTM!
