### ISSUE TITLE
Automatically Update Algolia Search Results

### ISSUE THREAD

**Issue by pglowacky** [livepeer/studio#796]
Currently, Algolia search crawler does not automatically update on a regular basis or when new docs are added to .com/docs

Algoia search results should be updated at least on a regular interval, or ideally, whenever changes are made to the docs.

**Comment by FullStackTiger** [comment]
@adamsoffer we don't use the python scraper repo for that or do you have another solution?

**Comment by adamsoffer** [comment]
@FullStackTiger let's move away from the manual python scraper we use currently and set up automatic scraping using github actions + Algolia DocSearch. [Here's](https://brunoscheufler.com/blog/2021-08-08-setting-up-algolia-docsearch-with-nextjs) a decent tutorial on how to set that up. Seems fairly straight forward. Think you can tackle this?

**Comment by FullStackTiger** [comment]
I set up automatic scraping using GitHub actions with cron job here:
https://github.com/livepeer/algolia-docsearch-scraper/commit/cb71bf8cf4787a979b19cf6bace71d5d98858426

The python scraper runs when pushing the code to the main branch, and at 00:00 every day.
It is working well now.
@adamsoffer @pglowacky

**Comment by adamsoffer** [comment]
@FullStackTiger Looks like the github action was set up properly. Nice work. Let's confirm it runs again as scheduled and then we can close this issue.

**Comment by FullStackTiger** [comment]
It is working well like this:

![image.png](https://images.zenhubusercontent.com/616efed4bc03b82db7d9e3ae/cf25361b-e486-474c-9554-f453d1a0e983)
