### ISSUE TITLE
Dashboard: Prevent users from turning recording on and off while a stream is active, remove warning for disabling recording

### ISSUE THREAD

**Issue by pglowacky** [livepeer/studio#797]
## Current Behavior

Video:
https://drive.google.com/file/d/1L4itstS4Q8KM2C8sqTv0gy38C9SOrbUl/view?usp=drivesdk

Currently, when a stream is active, you can turn recording on and off. When you turn it off, you get an alert describing the consequences of turning recording off. When you turn it on during a stream, you get a notification saying that recording has been turned on. 

## Desired Behavior

Customers cannot change their recording preferences while a session is active in a given stream. Therefore, this should be reflected in the dashboard. 

### When a stream is active...

-   and a user attempts to change the recording preferences on the dashboard, no visual changes are made and a notification pops up:

![image.png](https://images.zenhubusercontent.com/602ea479bcf4ef10a9aace61/0ef00b2a-c56a-42bd-8fd0-89ccdebcaf2e)

### When a stream is inactive...

- users are able to freely toggle between recording preferences with a notification only at the bottom of the screen (this is currently in place today). There is no need for a pop-up confirming the change in recording preferences.

**Comment by victorges** [comment]
Should this apply to changing multistream targets as well?

**Comment by pglowacky** [comment]
I'm glad you pointed this out. I think we have to make changes to multistream configuration consistent and prevent users from making changes to their stream while an active stream is in progress. Otherwise, it's too difficult to figure out which settings can be changed. It's easier to have the rule that no changes can be made to stream settings while a stream is in progress. 

What do you think? Do you think we need to change how we let users to make changes to multistream targets?

**Comment by FullStackTiger** [comment]
so should this apply to changing multistream targets?
@pglowacky @victorges

**Comment by pglowacky** [comment]
@FullStackTiger Yes. If a stream is active, I think we should show the error when they hit the "create" button on the stream detail page (rather than after they've filled out the multistream detail).

**Comment by FullStackTiger** [comment]
Also, should this apply to these two buttons too? @pglowacky 
![image.png](https://images.zenhubusercontent.com/616efed4bc03b82db7d9e3ae/b59b250f-088f-43c1-a429-f5a0f0fb9e12)

**Comment by victorges** [comment]
> Also, should this apply to these two buttons too?

Yeah, enabling/disabling a target is also unsupported while the stream is active.

**Comment by pglowacky** [comment]
I'm not seeing this implemented on my dashboard. @FullStackTiger has this been deployed?
