### ISSUE TITLE
homepage mobile hero gradient flicker

### ISSUE THREAD

**Issue by adamsoffer** [livepeer/studio#81]
**Describe the bug (required)**
On mobile the gradient on the home page hero flickers.
 
**Screenshots (optional)**
![hero](https://user-images.githubusercontent.com/555740/92670228-920b5100-f2e1-11ea-8418-65dcf7e32979.gif)

**Comment by adamsoffer** [comment]
Hey @julianbenegas! Just noticed this is still occurring on mobile. Any idea?

**Comment by julianbenegas** [comment]
@adamsoffer i think it's not specific to mobile, rather to Safari. I don't really know why it happens (thought i did). We can remove the slide effect in safari for now, wdyt?

**Comment by adamsoffer** [comment]
@julianbenegas it's not as pronounced, but I do notice a slight flicker on chrome and brave mobile as well. Might be worth exploring this animation technique instead https://css-tricks.com/infinite-all-css-scrolling-slideshow/
