### ISSUE TITLE
Chat bubble is blocking pagination on /dashboard/streams

### ISSUE THREAD

**Issue by pglowacky** [livepeer/studio#821]
From Tom at PlayDJ:

![image.png](https://images.zenhubusercontent.com/602ea479bcf4ef10a9aace61/458e2423-64ea-4214-aedc-8416d0c3efcc)

If we extend the page slightly, customers could continue scrolling, revealing the "Next" button

**Comment by pglowacky** [comment]
![image.png](https://images.zenhubusercontent.com/602ea479bcf4ef10a9aace61/3434f37c-4ea8-4b9b-a7e4-ce85d21d7999)

I'm still seeing this

**Comment by FullStackTiger** [comment]
> I'm still seeing this

Interesting, which URL did you review? .monster or .com? @pglowacky 

I can't see this issue on my side like this:
![image](https://user-images.githubusercontent.com/35409129/150593607-0d8a1e9a-6dff-4191-a533-931859e2954b.png)

**Comment by pglowacky** [comment]
I was on .com -- has it been deployed there yet?

**Comment by FullStackTiger** [comment]
yes, it is not deployed to the production(.com) yet.
