### ISSUE TITLE
Create "verify your email" banner on dashboard home

### ISSUE THREAD

**Issue by victorges** [livepeer/studio#825]
We currently ask for users to verify their emails on sign-up, but then never speak of it again to them.

We should remind the unverified users about that, since they won't be able to do things like recover their
password or get any communication from us if their email is wrong.

The banner should contain a button to re-send the verification email, in case they didn't get it or it went to
spam (something we can warn them after they click to re-send). This requires a new API to re-send the 
verification email. That API should only fire a new email if the user is not yet verified and there are not more
than 5 outstanding verification emails already sent (or some limit like that).

It could be a banner just like we have for upgrading to a pro plan, maybe even replacing it with a "verify your email"
for The Unverified, since we might not even be able/want to get a pro plan for a user can't reach out. Or if we want
to keep that possibility open (unverified user with pro plan), we can just add another banner in there and have them
stacked vertically.
![Screen Shot 2022-01-03 at 16.10.52.png](https://images.zenhubusercontent.com/60b6668d4787a4f864ebe378/62ee0e7b-04fb-456f-ae16-464714eb9e35)

It might also be a good idea to have a "re-send verification email" button on the verification page, in case there
is some error with the verification. There is currently no way of retrying or fixing it right now in case it fails, and 
that should be a way for that (given we also have the limits proposed above to avoid spam).

**Comment by FullStackTiger** [comment]
https://github.com/livepeer/livepeer-com/pull/931
