### ISSUE TITLE
Make sure our streams playback well in Decentraland

### ISSUE THREAD

**Issue by pglowacky** [livepeer/studio#834]
Do some basic testing to ensure solid playback in an environment like Decentraland

https://docs.decentraland.org/development-guide/video-playing/

**Comment by victorges** [comment]
We can build a scene locally with a video player and test if it works with the "preview scene" flow of the SDK. Should be easier and more accurate than testing only on a random Unity program.

https://docs.decentraland.org/development-guide/preview-scene/#preview-a-scene

I'll try to pick this up this week.
