### ISSUE TITLE
Cannot Navigate Between "https://livepeer.com/docs" and "https://livepeer.com/dashboard"

### ISSUE THREAD

**Issue by ericxtang** [livepeer/studio#917]
Currently, a developer cannot easily navigate between the dashboard and the docs.  The only way to go from dashboard to docs is through the "Get started tutorial" button in the welcome page.

We should have top-level navs that helps developers easily go between these two important sections of Livepeer Video Services.

**Comment by pglowacky** [comment]
@ericxtang I think we have this.  Right now there's the top-level navigation button to the dashboard whether you're logged in or not. Are you seeing something different? 

![image.png](https://images.zenhubusercontent.com/602ea479bcf4ef10a9aace61/76d43f59-221e-467c-a2bd-5b38c3a1db9b)

EDIT: GOT IT -- we need something in the dashboard to easily link to docs. The other direction than what I described :)

**Comment by hjpotter92** [comment]
it's hidden behind another icon. should have a clear visibility from developers tab in any case i think!

![image.png](https://images.zenhubusercontent.com/61c22559a5384e32a1ebf916/0f9bf16a-e75f-4fc2-844e-87faa4f678a1)

**Comment by ericxtang** [comment]
Ahh @pglowacky and @hjpotter92 - thanks for pointing out.

Let's make the nav consistent across the two sections - this is a pretty established pattern across many developer tools.

**Comment by pglowacky** [comment]
@FullStackTiger 

Currently there is a link to the documentation under the "?" at the top right corner of the Dashboard screen, visible on all pages. However, that is not prominent enough for users and needs to be more front and center. 

- Remove the link to the docs under "?"
- Using the same icons, move the link under the sidebar navigation:

![image.png](https://images.zenhubusercontent.com/602ea479bcf4ef10a9aace61/e1267642-ce0d-4c3c-9e3a-a7cf758c86f1)

**Comment by pglowacky** [comment]
Ah, missed these comments (they come through way more slowly via Zenhub)! Will work on getting a "dashboard" button drawn up with @adamsoffer for the top left hand nav.
