### ISSUE TITLE
Bug: Recordings are the wrong length

### ISSUE THREAD

**Issue by pglowacky** [livepeer/studio#940]
From DJMegaDisco:

I'm having problems with a recording - the set was 3 hours and 7 minutes, but when I try to download it, it only download a bit more then 400M and it's only 21 minutes long,  is there any way to recover it? 

From a different customer (not clear if it's related):

Why when I download a recorded stream (MP4) does the video metadata say it's only a few seconds long, and when played in Windows Media Player it only plays the first few seconds. However, when played in VLC it plays the full thing? Is this a known issue???

Labeling as a P1 issue due to customers potentially being unable to retrieve streams

**Comment by victorges** [comment]
FTR: This is the stream ID `3a244e1e-f1a5-4211-9842-05a9b77ca2dd` and here's what the dashboard shows:

<img width="1202" alt="unknown" src="https://user-images.githubusercontent.com/1613383/156003689-f5216e5f-3e9c-4c2a-b677-8fc059ddb841.png">

The second session with >3h is the one that is getting only a 21 min recording download.

**Comment by pglowacky** [comment]
Closing in favor of larger effort to fix recording
