### ISSUE TITLE
Reduce recording wait time to 10 seconds

### ISSUE THREAD

**Issue by pglowacky** [livepeer/studio#949]
Currently, there's a 5 minute delay from the completion of a stream to when Playback URLs / MP4 download links are ready. 

We've heard from users, especially those who are building FE applications with Livepeer, that the wait time is too long and breaks the user experience. 

If this is an easy change, let's change it from 5 minutes --> 10 seconds.

**Comment by iameli** [comment]
I'm going to say 10 seconds is a little aggressive in a world where we frequently see 8.3 second segments, but how 'bout 30 seconds?

**Comment by pglowacky** [comment]
Sounds good!

**Comment by victorges** [comment]
I think we could also make it a little higher, like 1 minute for example, but allow users to set the `forceUrl` query string which currently is only available to admins (arbitrarily)? Then we have a safer threshold for users to recover their connections and continue recordings on the same session, but still allow users – that know what they are doing – to forcefully request the recording URL, with the risk of missing some segments in the end (if those delay a bit for example).

This is what I'm referring to: https://github.com/livepeer/livepeer-com/blob/dffc577067cfc88c2c32876f2ff28491c77494c8/packages/api/src/controllers/stream.ts#L326
`if (isReady || (req.user.admin && forceUrl)) {`
becomes
`if (isReady || forceUrl) {`

WDYT?

**Comment by pglowacky** [comment]
Noting that we changed the wait time to 1 min, based on a Discord discussion with @gioelecerati and I. This needs to be reflected in documentation.
