### ISSUE TITLE
Written API Request: All streams for customer with total number of minutes streamed, by date

### ISSUE THREAD

**Issue by pglowacky** [livepeer/studio#950]
A customer wants to be able to charge their users each week for the number of minutes they've streamed. Each customer = stream. 

So, can I get a query that lists:

- Name of the stream
- Session created at date
- Number of minutes streamed per session

I'll be able to filter on Metabase by date range to pull a weekly list for them. 

DM me for customer's email.

**Comment by victorges** [comment]
I believe all this can be queried from the API. Would it be more appropriate to instruct them on how to query the API for that themselves?

**Comment by pglowacky** [comment]
@victorges Yes! That sounds great. I'll close this for now.

**Comment by pglowacky** [comment]
Talking with @victorges that this should be available to users in the API. This customer would like to pull minutes per stream between specific dates (theoretically, they'd be pulling these numbers every week). 

Can someone write me the API request that this person would use to do this? I may need some custom instructions on how to filter for dates.
