### ISSUE TITLE
DNS CNAME added for Discourse

### ISSUE THREAD

**Issue by Shih-Yu** [livepeer/studio#968]
Could @pglowacky or @iameli assist with the following?

1. > > You’ve chosen **forum.livepeer.com** as your Discourse address.>
2. > > You will need access to the DNS controls for your domain **livepeer.com**. It is usually accessible from the same place you purchased the **livepeer.com** domain name from.>
3. > > Add a DNS CNAME record that points **forum.livepeer.com** to **livepeer1.hosted-by-discourse.com**..>
![7724C9E1-B803-4C5C-9F6E-C4C9C6F873E8.png](https://images.zenhubusercontent.com/61fdb1f02502ef1db9860e14/850cef7d-c166-4b69-9b30-c160a35504d8)
(If you need help with DNS, see this [guide](https://meta.discourse.org/t/configure-your-domain-name-for-hosted-discourse/21827)).

After that,

• > > We’ll automatically monitor for your DNS update, and get your new Discourse site provisioned as soon as we see the change go live. DNS changes can take a little while to propagate.>
• > > You can [check the status here](https://payments.discourse.org/check_dns?fqdn=forum.livepeer.com).>
• > > Once your Discourse site is ready, you will get another email inviting you to sign up and become an admin.>
• > > After you log in for the first time, your free trial runs for the next 14 days, and can be extended if needed. Don’t worry, you will never be billed until you confirm that you wish to begin a hosting subscription with us.>

Note: if you do not get around to configuring your DNS in the next 24 hours, we’ll set you up on our trydiscourse.com trial domain so you can get started right away. If this happens, you will need to manually change the domain from your Discourse site’s admin panel before you can start your subscription.

**Comment by iameli** [comment]
Created!
