### ISSUE TITLE
Player on Stream Health page struggles with cold start

### ISSUE THREAD

**Issue by pglowacky** [livepeer/studio#973]
On the stream health page, the player struggles if the page is being viewed before a stream starts. When the stream starts it buffers (some initial buffering is expected) but sometimes the buffering lasts longer than I'd expect OR has several buffering events at the beginning of the stream. 

The player should have less startup buffering. Using [Bitmovin's test player for comparison](https://bitmovin.com/demos/stream-test), there's typically a few seconds of initial buffering and then smooth playback.

**Comment by Shih-Yu** [comment]
Couple more users experienced the same issue. 
https://discord.com/channels/423160867534929930/426114749370204170/1015222415036514355
https://discord.com/channels/423160867534929930/426114749370204170/1015304045507915847

Some suggestions:
-  having the page auto refresh when the stream starts
- adding a note on the page about refreshing when the stream starts
https://discord.com/channels/423160867534929930/426114749370204170/1015382057578410066

**Comment by pglowacky** [comment]
This is theoretically solved when we move to the Livepeer player in the dashboard.
